---
title: "Rpf - mutant"
author: "Venus Kuo"
date: "July 6, 2017"
output: html_document
---

# Set Directory
```{r, message=FALSE, warning=FALSE}
rm(list=ls())
getwd()
setwd("~/../Github/Rpf/mutant")
```

# Load packages

```{r, message=FALSE, warning=FALSE}
require("ggplot2")
require("plyr")
```

# Load data

```{r}
mutant <- read.csv("growthcurve.csv", head = TRUE)

enzchk <- read.csv("enzcheck.csv", head = TRUE)

trnc <- read.csv("trncgrowthcurve.csv", head = TRUE)

head(mutant)
head(enzchk)
head(trnc)

mutant$Experiment <- as.factor(mutant$Experiment)
mutant$Hour <- as.factor(mutant$Hour)

trnc$Hour <- as.factor(trnc$Hour)

enzchk$Experiment <- as.factor(enzchk$Experiment)
```

# Make figure of growth curves

```{r}
# Subset Rpf mutants # 
E54A <- subset(mutant, Experiment == "E54A")
E54K <- subset(mutant, Experiment == "E54K")
E54Q <- subset(mutant, Experiment == "E54Q")

# Calculate biomass means and standard errors of the means # 
E54A.means.sem <- ddply(E54A, c("Treatment"), summarise,
                   mean=mean(OD600), sem=sd(OD600)/sqrt(length(OD600)))
E54A.means.sem <- transform(E54A.means.sem, lower=mean-sem, upper=mean+sem)

E54K.means.sem <- ddply(E54K, c("Treatment"), summarise,
                   mean=mean(OD600), sem=sd(OD600)/sqrt(length(OD600)))
E54K.means.sem <- transform(E54K.means.sem, lower=mean-sem, upper=mean+sem)

E54Q.means.sem <- ddply(E54Q, c("Treatment"), summarise,
                   mean=mean(OD600), sem=sd(OD600)/sqrt(length(OD600)))
E54Q.means.sem <- transform(E54Q.means.sem, lower=mean-sem, upper=mean+sem)

# Calculate biomass means and sem for truncated growth curve # 
trnc.means.sem <- ddply(trnc, c("Treatment"), summarise,
                   mean=mean(OD600), sem=sd(OD600)/sqrt(length(OD600)))
trnc.means.sem <- transform(trnc.means.sem, lower=mean-sem, upper=mean+sem)

# Barplot of E54 mutant # 
E54A.barplot <- ggplot(E54A.means.sem, aes(x=Treatment,y = mean)) + 
  geom_bar(width=0.5, colour="black", fill="white" , position = position_dodge(width = 0.65), stat = "identity", size=1)

E54K.barplot <- ggplot(E54K.means.sem, aes(x=Treatment,y = mean)) + 
  geom_bar(width=0.5, colour="black", fill="white" , position = position_dodge(width = 0.65), stat = "identity", size=1)

E54Q.barplot <- ggplot(E54Q.means.sem, aes(x=Treatment,y = mean)) + 
  geom_bar(width=0.5, colour="black", fill="white" , position = position_dodge(width = 0.65), stat = "identity", size=1)

# Barplot of E54 mutant effects on biomass for pub figures # 
E54A.barplot + geom_errorbar(aes(ymax=upper, ymin=lower),
                              position=position_dodge(0.65), data=E54A.means.sem, width = 0.2, size=1) +
  labs(x="Treatment", y="Biomass Yeild (OD600)") +
  theme_classic() +
  scale_fill_manual(values=c("White", "Black")) +
  theme(axis.text.y=element_text(colour="black", size=16),
        axis.text.x=element_text(colour="black", size =14),
        axis.title=element_text(size=18),
        axis.title.y = element_text(colour="black",  margin = margin(0,25,0,10)),
        axis.title.x = element_text(colour="black",margin=margin(25,0,0,0)),
        panel.border = element_rect(linetype = "solid", colour = "black", size=1.5, fill=NA),
        axis.ticks.length = unit(.25, "cm"),
        axis.ticks = element_line(size = 1.5),
        legend.title = element_text(size=18),
        legend.text=element_text(size=18)) +
  annotate("text", x =0.55, y=2.7, label = c("A"), size=12)

E54K.barplot + geom_errorbar(aes(ymax=upper, ymin=lower),
                              position=position_dodge(0.65), data=E54K.means.sem, width = 0.2, size=1) +
  labs(x="Treatment", y="Biomass Yeild (OD600)") +
  theme_classic() +
  scale_fill_manual(values=c("White", "Black")) +
  theme(axis.text.y=element_text(colour="black", size=16),
        axis.text.x=element_text(colour="black", size =14),
        axis.title=element_text(size=18),
        axis.title.y = element_text(colour="black",  margin = margin(0,25,0,10)),
        axis.title.x = element_text(colour="black",margin=margin(25,0,0,0)),
        panel.border = element_rect(linetype = "solid", colour = "black", size=1.5, fill=NA),
        axis.ticks.length = unit(.25, "cm"),
        axis.ticks = element_line(size = 1.5),
        legend.title = element_text(size=18),
        legend.text=element_text(size=18))+
  annotate("text", x =0.55, y=2.7, label = c("B"), size=12)
  
E54Q.barplot + geom_errorbar(aes(ymax=upper, ymin=lower),
                              position=position_dodge(0.65), data=E54Q.means.sem, width = 0.2, size=1) +
  labs(x="Treatment", y="Biomass Yeild (OD600)") +
  theme_classic() +
  scale_fill_manual(values=c("White", "Black")) +
  theme(axis.text.y=element_text(colour="black", size=16),
        axis.text.x=element_text(colour="black", size =14),
        axis.title=element_text(size=18),
        axis.title.y = element_text(colour="black",  margin = margin(0,25,0,10)),
        axis.title.x = element_text(colour="black",margin=margin(25,0,0,0)),
        panel.border = element_rect(linetype = "solid", colour = "black", size=1.5, fill=NA),
        axis.ticks.length = unit(.25, "cm"),
        axis.ticks = element_line(size = 1.5),
        legend.title = element_text(size=18),
        legend.text=element_text(size=18))+
  annotate("text", x =0.55, y=2.25, label = c("C"), size=12)

# Barplot of truncated Rpf effects on KBS0714 biomass yeild # 
trnc.barplot <- ggplot(trnc.means.sem, aes(x=Treatment,y = mean)) + 
  geom_bar(width=0.5, colour="black", fill="white" , position = position_dodge(width = 0.65), stat = "identity", size=1)

trnc.barplot + geom_errorbar(aes(ymax=upper, ymin=lower),
                              position=position_dodge(0.65), data=trnc.means.sem, width = 0.2, size=1) +
  labs(x="Treatment", y="Biomass Yeild (OD600)") +
  theme_classic() +
  scale_fill_manual(values=c("White", "Black")) +
  theme(axis.text.y=element_text(colour="black", size=16),
        axis.text.x=element_text(colour="black", size =14),
        axis.title=element_text(size=18),
        axis.title.y = element_text(colour="black",  margin = margin(0,25,0,10)),
        axis.title.x = element_text(colour="black",margin=margin(25,0,0,0)),
        panel.border = element_rect(linetype = "solid", colour = "black", size=1.5, fill=NA),
        axis.ticks.length = unit(.25, "cm"),
        axis.ticks = element_line(size = 1.5),
        legend.title = element_text(size=18),
        legend.text=element_text(size=18))+
  annotate("text", x =0.55, y=2, label = c("D"), size=12)

```

# Run statistics for Rpf mutant effect on biomass yeild

```{r}
# E54A #
anova_exp1 <- aov(E54A$OD600 ~ E54A$Treatment, data = E54A)
summary(anova_exp1) # Treatment significantly affected OD600
TukeyHSD(anova_exp1) # 2.02 dif increase from E54A to WT Rpf
head(E54A.means.sem) # 258.97% redution in biomass, Tukey HSD p < 0.0001

# E54K # 
anova_exp2 <- aov(E54K$OD600 ~ E54K$Treatment, data = E54K)
summary(anova_exp2) # Treatment significantly affected OD600
TukeyHSD(anova_exp2) # 1.09 dif increase from E54K to WT Rpf
head(E54K.means.sem) # On average 64.50% decrease in biomass, Tukey HSD p < 0.0001

# E54Q # 
anova_exp3 <- aov(E54Q$OD600 ~ E54Q$Treatment, data = E54Q)
summary(anova_exp3) # Treatment significantly affected OD600
TukeyHSD(anova_exp3) # 0.58 dif increase from E54Q to WT Rpf
head(E54Q.means.sem) # On average 33.05% decrease in biomass, Tukey HSD p = 0.0005

# Truncated Rpf # 
anova_trnc <- aov(trnc$OD600 ~ trnc$Treatment, data  = trnc)
summary(anova_trnc)
TukeyHSD(anova_trnc)
head(trnc.means.sem)

```


# Make Barplot of Enzyme activity 

```{r}
# Subset Rpf mutants # 
E54A.e <- subset(enzchk, Experiment == "E54A")
E54K.e <- subset(enzchk, Experiment == "E54K")
E54Q.e <- subset(enzchk, Experiment == "E54Q")
trnc.e <- subset(enzchk, Experiment == "trnc")

# Calculate biomass means and standard errors of the means # 
E54A.e.means.sem <- ddply(E54A.e, c("Protein"), summarise,
                   mean=mean(Absorbance), sem=sd(Absorbance)/sqrt(length(Absorbance)))
E54A.e.means.sem <- transform(E54A.e.means.sem, lower=mean-sem, upper=mean+sem)

E54K.e.means.sem <- ddply(E54K.e, c("Protein"), summarise,
                   mean=mean(Absorbance), sem=sd(Absorbance)/sqrt(length(Absorbance)))
E54K.e.means.sem <- transform(E54K.e.means.sem, lower=mean-sem, upper=mean+sem)

E54Q.e.means.sem <- ddply(E54Q.e, c("Protein"), summarise,
                   mean=mean(Absorbance), sem=sd(Absorbance)/sqrt(length(Absorbance)))
E54Q.e.means.sem <- transform(E54Q.e.means.sem, lower=mean-sem, upper=mean+sem)

trnc.e.means.sem <- ddply(trnc.e, c("Protein"), summarise,
                   mean=mean(Absorbance), sem=sd(Absorbance)/sqrt(length(Absorbance)))
trnc.e.means.sem <- transform(trnc.e.means.sem, lower=mean-sem, upper=mean+sem)

# Barplot of bacterial gene abundance in soil # 
E54A.e.barplot <- ggplot(E54A.e.means.sem, aes(x=Protein,y = mean)) + 
  geom_bar(width=0.5, colour="black", fill="white" , position = position_dodge(width = 0.65), stat = "identity", size=1)

E54K.e.barplot <- ggplot(E54K.e.means.sem, aes(x=Protein,y = mean)) + 
  geom_bar(width=0.5, colour="black", fill="white" , position = position_dodge(width = 0.65), stat = "identity", size=1)

E54Q.e.barplot <- ggplot(E54Q.e.means.sem, aes(x=Protein,y = mean)) + 
  geom_bar(width=0.5, colour="black", fill="white" , position = position_dodge(width = 0.65), stat = "identity", size=1)

# Barplot of bacterial gene abundance in soil for pub figures # 
E54A.e.barplot + geom_errorbar(aes(ymax=upper, ymin=lower),
                              position=position_dodge(0.65), data=E54A.e.means.sem, width = 0.2, size=1) +
  labs(x="Treatment", y="Absorbance") +
  theme_classic() +
  scale_fill_manual(values=c("White", "Black")) +
  theme(axis.text.y=element_text(colour="black", size=16),
        axis.text.x=element_text(colour="black", size =14),
        axis.title=element_text(size=18),
        axis.title.y = element_text(colour="black",  margin = margin(0,25,0,10)),
        axis.title.x = element_text(colour="black",margin=margin(25,0,0,0)),
        panel.border = element_rect(linetype = "solid", colour = "black", size=1.5, fill=NA),
        axis.ticks.length = unit(.25, "cm"),
        axis.ticks = element_line(size = 1.5),
        legend.title = element_text(size=18),
        legend.text=element_text(size=18)) +
  annotate("text", x =0.55, y=38000, label = c("A"), size=12)

E54K.e.barplot + geom_errorbar(aes(ymax=upper, ymin=lower),
                              position=position_dodge(0.65), data=E54K.e.means.sem, width = 0.2, size=1) +
  labs(x="Treatment", y="Absorbance") +
  theme_classic() +
  scale_fill_manual(values=c("White", "Black")) +
  theme(axis.text.y=element_text(colour="black", size=16),
        axis.text.x=element_text(colour="black", size =14),
        axis.title=element_text(size=18),
        axis.title.y = element_text(colour="black",  margin = margin(0,25,0,10)),
        axis.title.x = element_text(colour="black",margin=margin(25,0,0,0)),
        panel.border = element_rect(linetype = "solid", colour = "black", size=1.5, fill=NA),
        axis.ticks.length = unit(.25, "cm"),
        axis.ticks = element_line(size = 1.5),
        legend.title = element_text(size=18),
        legend.text=element_text(size=18))+
  annotate("text", x =0.55, y=42000, label = c("B"), size=12)
  
E54Q.e.barplot + geom_errorbar(aes(ymax=upper, ymin=lower),
                              position=position_dodge(0.65), data=E54Q.e.means.sem, width = 0.2, size=1) +
  labs(x="Treatment", y="Absorbance") +
  theme_classic() +
  scale_fill_manual(values=c("White", "Black")) +
  theme(axis.text.y=element_text(colour="black", size=16),
        axis.text.x=element_text(colour="black", size =14),
        axis.title=element_text(size=18),
        axis.title.y = element_text(colour="black",  margin = margin(0,25,0,10)),
        axis.title.x = element_text(colour="black",margin=margin(25,0,0,0)),
        panel.border = element_rect(linetype = "solid", colour = "black", size=1.5, fill=NA),
        axis.ticks.length = unit(.25, "cm"),
        axis.ticks = element_line(size = 1.5),
        legend.title = element_text(size=18),
        legend.text=element_text(size=18))+
  annotate("text", x =0.55, y=40000, label = c("C"), size=12)
```


# Run statistics for Rpf mutant effect on enzymatic activity 

```{r}
# E54A #
anova_exp1 <- aov(E54A.e$Absorbance ~ E54A.e$Protein, data = E54A.e)
summary(anova_exp1) # Treatment significantly affected OD600
TukeyHSD(anova_exp1) # 2.02 dif increase from E54A to WT Rpf
head(E54A.e.means.sem) # 258.97% redution in biomass

# E54K # 
anova_exp2 <- aov(E54K.e$Absorbance ~ E54K.e$Protein, data = E54K.e)
summary(anova_exp2) # Treatment significantly affected OD600
TukeyHSD(anova_exp2) # 1.09 dif increase from E54K to WT Rpf
head(E54K.e.means.sem) # On average 36.3% decrease in biomass 

# E54Q # 
anova_exp3 <- aov(E54Q.e$Absorbance ~ E54Q.e$Protein, data = E54Q.e)
summary(anova_exp3) # Treatment significantly affected OD600
TukeyHSD(anova_exp3) # 0.58 dif increase from E54Q to WT Rpf
head(E54Q.e.means.sem) # On average 33.05% decrease in biomass 
```

# 



