---
title: "Rpf: generality"
author: "Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

Termination of dormancy in soil bacteria with resuscitation promoting factor (Rpf)

## Clear workspace and set directory

```{r setup}
rm(list=ls())
getwd()
setwd("~/GitHub/Rpf")
```

## Load packages and functions

```{r}
require("png")
require("dplyr")
require("grid")
require("psych")

sem <- function(x) sqrt(var(x)/length(x))
LL.95 <- function(x) t.test(x)$conf.int[1]
UL.95 <- function(x) t.test(x)$conf.int[2]

```

## Load and process growth data

```{r}
# Load parameters from Gompertz analysis of growth curves
gc.param.1 <- read.delim("data/generality/20160320_generality_gomp_param_output.txt", sep = ",", header = TRUE)
gc.param.2 <- read.delim("data/generality/20160323_generality_gomp_param_output.txt", sep = ",", header = TRUE)

# Load key associated with growth curve experiment 
gc.key <- read.delim("data/generality/generality.gc.well.key.txt", sep = "\t", header = TRUE)

# Merge data and key for data sets
key.1 <- subset(gc.key, Run_Num == "1", select = c(Strain,Gram,Phylum,Genus,Treatment,Rep))
gc.param.1 <- cbind(gc.param.1,key.1)
key.2 <- subset(gc.key, Run_Num == "2", select = c(Strain,Gram,Phylum,Genus,Treatment,Rep))
gc.param.2 <- cbind(gc.param.2,key.2)

# Merge data sets
gc <- rbind(gc.param.1, gc.param.2)

# Remove unused parameters to simplify
gc <- gc[ ,c(-(1:2),-(6:10))]

# Yield parameter (A) sometimes reported as negative; take absolute value
gc$A <- abs(gc$A)

# Time recorded in minutes; report lag and umax in hours
gc$L <-gc$L/60
gc$umax <-gc$umax/60

# Round up small negative estimates of lag for KBS0702 to zero
gc[6,3] = 0
gc[8,3] = 0
```

# Subset data

```{r}
# Order df.table

sort.strain <- c("KBS0812", "KBS0724", "KBS0706", "KBS0702", "KBS0703", 
                 "KBS0714", "KBS0715", "KBS0701", "KBS0711", "KBS0712", 
                 "KBS0710", "KBS0705")

gc.2 <- gc %>%
  mutate(Strain =  factor(Strain, levels = sort.strain)) %>%
  arrange(Strain) 

# Yield (A) for +Rpf 
A.plus <- filter(gc.2, Treatment == "Rpf+") %>%
   dplyr::select(A, Strain) %>%
   group_by(Strain) %>%
   summarize(mean.A = mean(A), SE.A = sem(A))

# Yield (A) for -Rpf 
A.minus <- filter(gc.2, Treatment == "Rpf-") %>%
   dplyr::select(A, Strain) %>%
   group_by(Strain) %>%
   summarize(mean.A = mean(A), SE.A = sem(A))

# Max growth (umax) for +Rpf 
umax.plus <- filter(gc.2, Treatment == "Rpf+") %>%
   dplyr::select(umax, Strain) %>%
   group_by(Strain) %>%
   summarize(mean.umax = mean(umax), SE.umax = sem(umax)) 

# Max growth (umax) for -Rpf 
umax.minus <- filter(gc.2, Treatment == "Rpf-") %>%
   dplyr::select(umax, Strain) %>%
   group_by(Strain) %>%
   summarize(mean.umax = mean(umax), SE.umax = sem(umax)) 

# Lag time (L) for +Rpf 
L.plus <- filter(gc.2, Treatment == "Rpf+") %>%
   dplyr::select(L, Strain) %>%
   group_by(Strain) %>%
   summarize(mean.L = mean(L), SE.L = sem(L)) 

# Lag time (L) for -Rpf 
L.minus <- filter(gc.2, Treatment == "Rpf-") %>%
   dplyr::select(L, Strain) %>%
   group_by(Strain) %>%
   summarize(mean.L = mean(L), SE.L = sem(L)) 
```


# Make figure

```{r}
png(filename="~/GitHub/Rpf/figures/Fig6a.png",
    width = 1200, height = 1200, res = 96*2, bg = "white")

plot.new()
par(oma=c(9,5,0,0), mar=c(1,2,1,1), mfrow = c(3,1))
 
# Created x-axis plotting locations
x.Rpf.minus <- seq(from = 1, to = 46, by = 4)
x.Rpf.plus <- seq(from = 2, to = 46, by = 4)

# Plot means for yield
plot(x.Rpf.minus, A.minus$mean.A, ylim = c(0, 2.5), xlim = c(0, 46), 
     pch = 22, col = "black", bg = "white", lwd = 1, cex = 2.25, yaxt = "n", 
     xaxt = "n", cex.lab = 2, cex.axis = 1.5, las = 1, ylab = "", xlab = "")
      box(lwd = 2)
      
points(x.Rpf.plus, A.plus$mean.A, pch = 22, col = "black", bg = "grey", 
       lwd = 1, cex = 2.25)

# Plot -Rpf errors
arrows(x0 = x.Rpf.minus, y0 = A.minus$mean.A, 
       y1 = (A.minus$mean.A + A.minus$SE.A), angle = 90, length = 0.02, lwd = 1.5)

arrows(x0 = x.Rpf.minus, y0 = A.minus$mean.A, 
       y1 = (A.minus$mean.A - A.minus$SE.A), angle = 90, length = 0.02, lwd = 1.5)

# Plot +Rpf errors
arrows(x0 = x.Rpf.plus, y0 = A.plus$mean.A, 
       y1 = (A.plus$mean.A + A.plus$SE.A), angle = 90, length = 0.02, lwd = 1.5)

arrows(x0 = x.Rpf.plus, y0 = A.plus$mean.A, 
       y1 = (A.plus$mean.A - A.plus$SE.A), angle = 90, length = 0.02, lwd = 1.5)

# Major Axes

x.int <-seq(from = 1.5, to = 46, by = 4)
axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = F, at = x.int, las =3)

axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("0.0", "0.5", "1.0", "1.5", "2.0", "2.5"), at = c(0,0.5,1.0,1.5,2.0,2.5))

axis(side = 4, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at = c(0,0.5,1.0,1.5,2.0, 2.5), labels = F)

axis(side = 3, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at = x.int, labels = F)

mtext(expression('Yield (OD600)'), side = 2,
      outer = FALSE, cex = 1.25, line = 4, adj = 0.5)

# Add p-values
text(5.75, 2.4, labels = expression("Treatment x Strain:" ~italic("P")~"< 0.0001"), cex = 1)

legend(42, 2.5, c("-Rpf", "+Rpf"), pch = 22, pt.bg = c("white", "grey"), 
       pt.cex = 2, pt.lwd = 1, bty = 'n', y.intersp = 1)


# Plot means for umax
plot(x.Rpf.minus, umax.minus$mean.umax, ylim = c(1e-07, 6e-05), xlim = c(0, 46), 
     pch = 22, col = "black", bg = "white", lwd = 1, cex = 2.25, yaxt = "n", 
     xaxt = "n", cex.lab = 2, cex.axis = 1.5, las = 1, ylab = "", xlab = "")
      box(lwd = 2)
      
points(x.Rpf.plus, umax.plus$mean.umax, pch = 22, col = "black", bg = "grey", 
       lwd = 1, cex = 2.25)

# Plot -Rpf errors
arrows(x0 = x.Rpf.minus, y0 = umax.minus$mean.umax, 
       y1 = (umax.minus$mean.umax + umax.minus$SE.umax), angle = 90, length = 0.02, lwd = 1.5)

arrows(x0 = x.Rpf.minus, y0 = umax.minus$mean.umax, 
       y1 = (umax.minus$mean.umax - umax.minus$SE.umax), angle = 90, length = 0.02, lwd = 1.5)

# Plot +Rpf errors
arrows(x0 = x.Rpf.plus, y0 = umax.plus$mean.umax, 
       y1 = (umax.plus$mean.umax + umax.plus$SE.umax), angle = 90, length = 0.02, lwd = 1.5)

arrows(x0 = x.Rpf.plus, y0 = umax.plus$mean.umax, 
       y1 = (umax.plus$mean.umax - umax.plus$SE.umax), angle = 90, length = 0.02, lwd = 1.5)

# Major Axes
x.int <-seq(from = 1.5, to = 46, by = 4)
axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = F, at = x.int, las =3)

axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("1e-05","3e-05","5e-05"), at = c(1e-05,  3e-05, 5e-05))

axis(side = 4, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at = c(1e-05,  3e-05, 5e-05), labels = F)

axis(side = 3, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at = x.int, labels = F)
  
mtext(expression(mu [max]* ' (hr'^-1*')'), side = 2,
 outer = FALSE, cex = 1.25, line = 4, adj = 0.5)

# Add p-values
text(5.5, 5.6e-05, labels = expression("Treatment x Strain:" ~italic("P")~"= 0.004"), cex = 1)


# Plot means for Lag
plot(x.Rpf.minus, L.minus$mean.L, ylim = c(0, 45), xlim = c(0, 46), 
     pch = 22, col = "black", bg = "white", lwd = 1, cex = 2.25, yaxt = "n", 
     xaxt = "n", cex.lab = 2, cex.axis = 1.5, las = 1, ylab = "", xlab = "")
      box(lwd = 2)
      
points(x.Rpf.plus, L.plus$mean.L, pch = 22, col = "black", bg = "grey", 
       lwd = 1, cex = 2.25)

# Plot -Rpf errors
arrows(x0 = x.Rpf.minus, y0 = L.minus$mean.L, 
       y1 = (L.minus$mean.L + L.minus$SE.L), angle = 90, length = 0.02, lwd = 1.5)

arrows(x0 = x.Rpf.minus, y0 = L.minus$mean.L, 
       y1 = (L.minus$mean.L - L.minus$SE.L), angle = 90, length = 0.02, lwd = 1.5)

# Plot +Rpf errors
arrows(x0 = x.Rpf.plus, y0 = L.plus$mean.L, 
       y1 = (L.plus$mean.L + L.plus$SE.L), angle = 90, length = 0.02, lwd = 1.5)

arrows(x0 = x.Rpf.plus, y0 = L.plus$mean.L, 
       y1 = (L.plus$mean.L - L.plus$SE.L), angle = 90, length = 0.02, lwd = 1.5)

# Major Axes
x.int <-seq(from = 1.5, to = 46, by = 4)

axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = sort.strain, at = x.int, las =3, col.axis = "gray40")

axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("0", "10", "20", "30","40"), at = c(0,10,20,30,40))

axis(side = 4, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at = c(0,10,20,30,40), labels = F)

axis(side = 3, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at = x.int, labels = F)

mtext(expression('Lag time (hr)'), side = 2,
      outer = FALSE, cex = 1.25, line = 4, adj = 0.5)

# Add p-values
text(3, 42, labels = expression("Strain:" ~italic("P")~"= 0.009"), cex = 1)
text(4.2, 33, labels = expression("Treatment:" ~italic("P")~"< 0.0001"), cex = 1)

# Add taxon names and lines
mtext('Gram +', side = 1, line = 8, at = 15, cex = 1.25)
mtext('Gram -', side = 1, line = 8, at = 37, cex = 1.25)

par(xpd=NA)
segments(1, -35, 26, -35, col = "black", lwd = 2)
segments(29, -35, 46, -35, col = "black", lwd = 2)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("./figures/Fig6a.png")

grid.raster(img)
```

 