---
title: "Rpf"
author: "Jay T. Lennon and Venus Kuo"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

Generality of Rpf on KBS bacterial isolates

# Set up working environment

```{r setup}
rm(list=ls())
getwd()
knitr::opts_knit$set(root.dir = '~/../GitHub/Rpf') 

sem <- function(x) sqrt(var(x)/length(x))
```


```{r}
require('ggplot2')
require('plyr')

# Load data set # 
rel_bio <- read.delim("data/generality-dose/Generality_DoseResponse_KBS0714_pixel.txt", sep = ",", header = TRUE)

# Log transform Rpf concentration # 
rel_bio['Rpf_Conc_log10'] = log10((rel_bio$Rpf_Conc + 1))

# Calculate Relative biomass on plates # 
rel_bio['Rel_Biomass'] = rel_bio['Biomass_Pixel'] / rel_bio['Total_Pixel']
rel_bio['Rel_Biomass'] = round(rel_bio['Rel_Biomass'], digits = 3)

# Plot scatter plot of relationship # 
plot(rel_bio$Rpf_Conc_log10, rel_bio$Rel_Biomass)

# Plot line graph of Rpf vs Relative biomass 

rel_bio.means.sem <- ddply(rel_bio, c("Rpf_Conc"), summarise,
                   mean=mean(Rel_Biomass), sem=sd(Rel_Biomass)/sqrt(length(Rel_Biomass)))
rel_bio.means.sem <- transform(rel_bio.means.sem, lower=mean-sem, upper=mean+sem)

pd <- position_dodge(0)

ggplot(rel_bio.means.sem, aes(x=Rpf_Conc, y=mean)) + 
  geom_errorbar(aes(ymax=upper, ymin=lower), position=position_dodge(0), 
                data=rel_bio.means.sem, width = 0.2, size=1) +
    geom_line(position=pd, size=2) +
    geom_point() +
    xlab("Rpf Concentrations") +
    ylab("Relative Biomass") +
    theme_classic() +
    theme(axis.text.y=element_text(colour="black", size=18),
          axis.text.x=element_text(colour="black", size=20),
          axis.title.y = element_text(size = 19, colour="black",  margin = margin(0,10,0,0)),
          axis.title.x = element_text(size = 20,colour="black",margin=margin(15,10,0,10)),
          panel.border = element_rect(linetype = "solid", colour = "black", size=2, fill=NA))

ggplot(data=rel_bio, aes(x=Rpf_Conc_log10, y=Rel_Biomass, group=1)) +
  geom_line()+
  geom_point()
```









