---
title: "Rpf: dose-response"
author: "Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

Termination of dormancy in soil bacteria with resuscitation promoting factor (Rpf)

## Clear workspace and set directory

```{r setup}
rm(list=ls())
getwd()
setwd("~/GitHub/Rpf")
```

## Load packages and functions

```{r}
require("png")
require("dplyr")
require("grid")
require("plyr")
require("tidyverse")
require("bbmle")
```

```{r}
# Load data
dose.raw <- read.table("data/dose.response/dose.response.48well.txt", 
            header = TRUE, sep="\t")

# calculate mean of the no-cell media wells
media <- filter(dose.raw, cell == "no") %>%
  dplyr::summarise(mean.med = mean(hist))

# subtract media-only from all wells containing cells
cells <- filter(dose.raw, cell == "yes") %>%
  mutate(cells, corr.hist = hist - 103.5393)

# calculate sum of biomass for each row across rpf concentration
sum.by.row <- cells %>%
  select(row, corr.hist) %>%
  group_by(row) %>%
  dplyr::summarise(row.sum = sum(corr.hist))
  
# calculate sum of biomass for each row across rpf concentration
prop.biomass.A <- filter(cells, row == "A") %>%
   mutate(prop.biomass.A, prop.b = corr.hist / 404)
prop.biomass.B <- filter(cells, row == "B") %>%
   mutate(prop.biomass.B, prop.b = corr.hist / 427)
prop.biomass.C <- filter(cells, row == "C") %>%
   mutate(prop.biomass.C, prop.b = corr.hist / 435)
prop.biomass.D <- filter(cells, row == "D") %>%
   mutate(prop.biomass.D, prop.b = corr.hist / 465)
prop.biomass.E <- filter(cells, row == "E") %>%
   mutate(prop.biomass.E, prop.b = corr.hist / 463)
prop.biomass.F <- filter(cells, row == "F") %>%
   mutate(prop.biomass.F, prop.b = corr.hist / 441)

prop.biomass <- rbind(prop.biomass.A, prop.biomass.B, prop.biomass.C, prop.biomass.D, 
      prop.biomass.E, prop.biomass.F)
```


## Fit Monod equation with maximum likelihood

```{r} 
# Starting values for fitting Monod maximum likelihood
V = 125 #85000
K = 1 #0.025
Z = 10 #100

fit <- mle2(cells[,7] ~ dnorm(mean = v * cells[,4] / (k + cells[,4]), sd = z), 
    start = list(v = V, k = K, z = Z), data = cells)
```


# Plot data and function

```{r}
png(filename="~/GitHub/Rpf/figures/Fig5A.png",
    width = 1200, height = 1200, res = 96*2) 

plot.new()
par(mar = c(7, 7, 5, 7))

plot(cells[,4], cells[,7], xlim = c(-1, 7), 
     ylim = c(-0.025, 140), type = "p", 
     pch = 22, bg = "grey", col = "black", cex = 2, ylab = "", xlab = "", 
     cex.lab = 1.5, las = 1, lwd = 2, yaxt = "n", xaxt = "n")
box(lwd=2)

# Add ticks and tick labels
axis(side = 2, lwd.ticks = 2, las = 1, cex.axis = 1.25, 
   labels = c(0, 50, 100, 150), at = c(0, 50, 100, 150))

axis(side = 4, labels = F, lwd.ticks = 2, 
   at = c(0, 50, 100, 150))

axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1, mgp = c(3, 1, 0),
    labels = c(0, 2, 4, 6), at = c(0, 2, 4, 6))

axis(side = 3, labels = F, lwd.ticks = 2, las = 1, cex.axis = 1.25, 
   at = c(0, 2, 4, 6))

#mtext('Rpf (nM)', side = 1, outer = TRUE, cex = 1.5, 
#      line = -4, adj = 0.5)

mtext(expression(paste('Rpf (', mu, 'M)')), side = 1, outer = TRUE, 
      cex = 1.5, line = -4, adj = 0.5)
      
mtext(expression(paste('Biomass (OD)')), 
      side = 2, outer = TRUE, cex = 1.5, line = -3, adj = 0.6)

# Plot function
curve((coef(fit)[[1]] * x) / (coef(fit)[[2]] + x), from = 0.05, 
      to = 6, add = TRUE, lty = 2, lwd = 2.5)


#curve(coef(fit)[[1]] * exp(-(x-coef(fit)[[2]]) * coef(fit)[[4]] * sign(coef(fit)[[2]] - x) * 
#      coef(fit)[[3]]^sign(coef(fit)[[2]]-x)),from = 0, to = 160, add = TRUE, lty = 2, lwd = 2.5)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("./figures/Fig5A.png")
grid.raster(img)
```

