---
title: "Rpf - antibody"
author: "Venus Kuo"
date: "July 6, 2017"
output: html_document
---

# Set Directory
```{r}
rm(list=ls())
getwd()
setwd("C:/Users/Venus/Github/Rpf/antibody")
```

# Load packages

```{r}
require("ggplot2")
require("plyr")
```

# Load data

```{r}
biomass <- read.csv("antibody.csv", head = TRUE)

head(biomass)

biomass$Hour <- as.factor(biomass$Hour)
```

# Make figure

```{r}
# Final biomass yeild based on treatment type # 
biomass.means <- ddply(biomass, c("Treatment"), summarise, mean=mean(OD600))

# Barplot # 
biomass.barplot <- ggplot(biomass.means, aes(x=Treatment,y = mean)) + 
  geom_bar(width=0.5, colour="black", fill="white" , position = position_dodge(width = 0.65), stat = "identity", size=1)

# Calculate standard errors of the means # 
biomass.means.sem <- ddply(biomass, c("Treatment"), summarise,
                   mean=mean(OD600), sem=sd(OD600)/sqrt(length(OD600)))
biomass.means.sem <- transform(biomass.means.sem, lower=mean-sem, upper=mean+sem)

# Barplot of final biomass based on treatment for pub figures # 
biomass.barplot + geom_errorbar(aes(ymax=upper, ymin=lower),
                              position=position_dodge(0.65), data=biomass.means.sem, width = 0.2, size=1) +
  labs(x="Treatment", y="Biomass Yield (OD600)") +
  theme_classic() +
  scale_fill_manual(values="White") +
  theme(axis.text.y=element_text(colour="black", size=16),
        axis.text.x=element_text(colour="black", size =14),
        axis.title=element_text(size=18),
        axis.title.y = element_text(colour="black",  margin = margin(0,25,0,10)),
        axis.title.x = element_text(colour="black",margin=margin(25,0,0,0)),
        panel.border = element_rect(linetype = "solid", colour = "black", size=1.5, fill=NA),
        axis.ticks.length = unit(.25, "cm"),
        axis.ticks = element_line(size = 1.5),
        legend.title = element_text(size=18),
        legend.text=element_text(size=18)) 
```

# Run statistics

```{r}
anova_exp1 <- aov(biomass$OD600 ~ biomass$Treatment, data = biomass)

summary(anova_exp1)

TukeyHSD(anova_exp1)

# Treatment had a significant effect on OD600 
# With the biggest difference between Rpf+ and Rpf+Anti28
```



