

Using BFGS method to optimize GTR rate parameters, to disable this specify "--no-bfgs" 



This is RAxML version 8.2.11 released by Alexandros Stamatakis on June 2017.

With greatly appreciated code contributions by:
Andre Aberer      (HITS)
Simon Berger      (HITS)
Alexey Kozlov     (HITS)
Kassian Kobert    (HITS)
David Dao         (KIT and HITS)
Sarah Lutteropp   (KIT and HITS)
Nick Pattengale   (Sandia)
Wayne Pfeiffer    (SDSC)
Akifumi S. Tanabe (NRIFS)
Charlie Taylor    (UF)


Alignment has 646 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 5.12%

RAxML rapid bootstrapping and subsequent ML search

Using 1 distinct models/data partitions with joint branch length optimization



Executing 1000 rapid bootstrap inferences and thereafter a thorough ML search 

All free model parameters will be estimated by RAxML
GAMMA model of rate heterogeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 646
Name: No Name Provided
DataType: DNA
Substitution Matrix: GTR




RAxML was called as follows:

raxmlHPC-PTHREADS -T 4 -f a -m GTRGAMMA -p 12345 -x 12345 -o Prochlorococcus -# autoMRE -s ./20180425_KBS -n KBS.ML 



Time for BS model parameter optimization 0.066731
Bootstrap[0]: Time 0.238277 seconds, bootstrap likelihood -9352.870667, best rearrangement setting 13
Bootstrap[1]: Time 0.160618 seconds, bootstrap likelihood -9253.375047, best rearrangement setting 13
Bootstrap[2]: Time 0.156700 seconds, bootstrap likelihood -8987.097343, best rearrangement setting 12
Bootstrap[3]: Time 0.141709 seconds, bootstrap likelihood -9426.268850, best rearrangement setting 15
Bootstrap[4]: Time 0.151252 seconds, bootstrap likelihood -8969.432065, best rearrangement setting 10
Bootstrap[5]: Time 0.134764 seconds, bootstrap likelihood -9418.228315, best rearrangement setting 10
Bootstrap[6]: Time 0.119429 seconds, bootstrap likelihood -9239.721637, best rearrangement setting 6
Bootstrap[7]: Time 0.126935 seconds, bootstrap likelihood -9328.315369, best rearrangement setting 14
Bootstrap[8]: Time 0.131061 seconds, bootstrap likelihood -9179.927854, best rearrangement setting 5
Bootstrap[9]: Time 0.119143 seconds, bootstrap likelihood -9076.406500, best rearrangement setting 7
Bootstrap[10]: Time 0.051399 seconds, bootstrap likelihood -8879.420887, best rearrangement setting 7
Bootstrap[11]: Time 0.056148 seconds, bootstrap likelihood -9218.837838, best rearrangement setting 5
Bootstrap[12]: Time 0.055669 seconds, bootstrap likelihood -9330.407248, best rearrangement setting 8
Bootstrap[13]: Time 0.097528 seconds, bootstrap likelihood -9426.927890, best rearrangement setting 7
Bootstrap[14]: Time 0.063572 seconds, bootstrap likelihood -9137.910913, best rearrangement setting 12
Bootstrap[15]: Time 0.133031 seconds, bootstrap likelihood -9085.540054, best rearrangement setting 15
Bootstrap[16]: Time 0.135891 seconds, bootstrap likelihood -9061.558780, best rearrangement setting 12
Bootstrap[17]: Time 0.161789 seconds, bootstrap likelihood -9459.229469, best rearrangement setting 12
Bootstrap[18]: Time 0.151055 seconds, bootstrap likelihood -8980.091681, best rearrangement setting 5
Bootstrap[19]: Time 0.120378 seconds, bootstrap likelihood -8828.399707, best rearrangement setting 8
Bootstrap[20]: Time 0.057090 seconds, bootstrap likelihood -9353.813571, best rearrangement setting 10
Bootstrap[21]: Time 0.054444 seconds, bootstrap likelihood -9127.423592, best rearrangement setting 6
Bootstrap[22]: Time 0.056724 seconds, bootstrap likelihood -9270.368544, best rearrangement setting 5
Bootstrap[23]: Time 0.126330 seconds, bootstrap likelihood -9219.258425, best rearrangement setting 7
Bootstrap[24]: Time 0.123508 seconds, bootstrap likelihood -9485.318271, best rearrangement setting 8
Bootstrap[25]: Time 0.114055 seconds, bootstrap likelihood -9230.750213, best rearrangement setting 6
Bootstrap[26]: Time 0.053742 seconds, bootstrap likelihood -9177.072043, best rearrangement setting 12
Bootstrap[27]: Time 0.158125 seconds, bootstrap likelihood -9339.440650, best rearrangement setting 10
Bootstrap[28]: Time 0.158165 seconds, bootstrap likelihood -9244.770062, best rearrangement setting 11
Bootstrap[29]: Time 0.121373 seconds, bootstrap likelihood -9039.387687, best rearrangement setting 12
Bootstrap[30]: Time 0.057967 seconds, bootstrap likelihood -9165.309244, best rearrangement setting 15
Bootstrap[31]: Time 0.133722 seconds, bootstrap likelihood -9113.466250, best rearrangement setting 15
Bootstrap[32]: Time 0.127949 seconds, bootstrap likelihood -9106.920129, best rearrangement setting 6
Bootstrap[33]: Time 0.142586 seconds, bootstrap likelihood -9239.500377, best rearrangement setting 15
Bootstrap[34]: Time 0.157636 seconds, bootstrap likelihood -8961.460912, best rearrangement setting 11
Bootstrap[35]: Time 0.074881 seconds, bootstrap likelihood -9222.212365, best rearrangement setting 8
Bootstrap[36]: Time 0.053181 seconds, bootstrap likelihood -9297.394745, best rearrangement setting 9
Bootstrap[37]: Time 0.057030 seconds, bootstrap likelihood -9487.599004, best rearrangement setting 11
Bootstrap[38]: Time 0.108585 seconds, bootstrap likelihood -9107.231141, best rearrangement setting 8
Bootstrap[39]: Time 0.122824 seconds, bootstrap likelihood -9278.543165, best rearrangement setting 13
Bootstrap[40]: Time 0.054526 seconds, bootstrap likelihood -9290.931396, best rearrangement setting 13
Bootstrap[41]: Time 0.125110 seconds, bootstrap likelihood -9347.477961, best rearrangement setting 10
Bootstrap[42]: Time 0.130661 seconds, bootstrap likelihood -9499.743857, best rearrangement setting 5
Bootstrap[43]: Time 0.054897 seconds, bootstrap likelihood -9183.545704, best rearrangement setting 14
Bootstrap[44]: Time 0.057583 seconds, bootstrap likelihood -9198.364085, best rearrangement setting 10
Bootstrap[45]: Time 0.108810 seconds, bootstrap likelihood -9091.391924, best rearrangement setting 15
Bootstrap[46]: Time 0.055607 seconds, bootstrap likelihood -8905.739434, best rearrangement setting 14
Bootstrap[47]: Time 0.139747 seconds, bootstrap likelihood -9052.247147, best rearrangement setting 8
Bootstrap[48]: Time 0.140209 seconds, bootstrap likelihood -8986.806098, best rearrangement setting 6
Bootstrap[49]: Time 0.113358 seconds, bootstrap likelihood -8874.391305, best rearrangement setting 7
Bootstrap[50]: Time 0.055986 seconds, bootstrap likelihood -8992.836790, best rearrangement setting 7
Bootstrap[51]: Time 0.116424 seconds, bootstrap likelihood -9234.813465, best rearrangement setting 11
Bootstrap[52]: Time 0.119308 seconds, bootstrap likelihood -9038.802048, best rearrangement setting 12
Bootstrap[53]: Time 0.055455 seconds, bootstrap likelihood -8865.415208, best rearrangement setting 8
Bootstrap[54]: Time 0.122995 seconds, bootstrap likelihood -9130.973259, best rearrangement setting 9
Bootstrap[55]: Time 0.124997 seconds, bootstrap likelihood -9180.492850, best rearrangement setting 11
Bootstrap[56]: Time 0.124072 seconds, bootstrap likelihood -9303.896573, best rearrangement setting 5
Bootstrap[57]: Time 0.127256 seconds, bootstrap likelihood -8841.084747, best rearrangement setting 7
Bootstrap[58]: Time 0.127331 seconds, bootstrap likelihood -9235.660688, best rearrangement setting 10
Bootstrap[59]: Time 0.054985 seconds, bootstrap likelihood -8796.547321, best rearrangement setting 9
Bootstrap[60]: Time 0.123310 seconds, bootstrap likelihood -9359.871182, best rearrangement setting 7
Bootstrap[61]: Time 0.129342 seconds, bootstrap likelihood -9116.506673, best rearrangement setting 5
Bootstrap[62]: Time 0.114912 seconds, bootstrap likelihood -9110.438483, best rearrangement setting 11
Bootstrap[63]: Time 0.125149 seconds, bootstrap likelihood -9248.018452, best rearrangement setting 12
Bootstrap[64]: Time 0.115966 seconds, bootstrap likelihood -9409.375729, best rearrangement setting 7
Bootstrap[65]: Time 0.400618 seconds, bootstrap likelihood -9388.149186, best rearrangement setting 5
Bootstrap[66]: Time 0.161686 seconds, bootstrap likelihood -8901.490863, best rearrangement setting 5
Bootstrap[67]: Time 0.127681 seconds, bootstrap likelihood -9142.577483, best rearrangement setting 15
Bootstrap[68]: Time 0.144965 seconds, bootstrap likelihood -9272.064248, best rearrangement setting 11
Bootstrap[69]: Time 0.148091 seconds, bootstrap likelihood -8920.117272, best rearrangement setting 5
Bootstrap[70]: Time 0.130356 seconds, bootstrap likelihood -9391.560952, best rearrangement setting 8
Bootstrap[71]: Time 0.120993 seconds, bootstrap likelihood -9367.193824, best rearrangement setting 10
Bootstrap[72]: Time 0.124878 seconds, bootstrap likelihood -9233.411239, best rearrangement setting 11
Bootstrap[73]: Time 0.170011 seconds, bootstrap likelihood -8842.654963, best rearrangement setting 9
Bootstrap[74]: Time 0.150839 seconds, bootstrap likelihood -9356.846541, best rearrangement setting 5
Bootstrap[75]: Time 0.166729 seconds, bootstrap likelihood -8934.824888, best rearrangement setting 8
Bootstrap[76]: Time 0.162273 seconds, bootstrap likelihood -9062.240173, best rearrangement setting 9
Bootstrap[77]: Time 0.129443 seconds, bootstrap likelihood -9165.067549, best rearrangement setting 11
Bootstrap[78]: Time 0.138809 seconds, bootstrap likelihood -9152.541403, best rearrangement setting 15
Bootstrap[79]: Time 0.064611 seconds, bootstrap likelihood -9504.109897, best rearrangement setting 9
Bootstrap[80]: Time 0.126310 seconds, bootstrap likelihood -9181.854091, best rearrangement setting 15
Bootstrap[81]: Time 0.143912 seconds, bootstrap likelihood -9170.172719, best rearrangement setting 7
Bootstrap[82]: Time 0.129943 seconds, bootstrap likelihood -9441.236863, best rearrangement setting 6
Bootstrap[83]: Time 0.117634 seconds, bootstrap likelihood -8927.094576, best rearrangement setting 10
Bootstrap[84]: Time 0.057964 seconds, bootstrap likelihood -9291.996512, best rearrangement setting 11
Bootstrap[85]: Time 0.054614 seconds, bootstrap likelihood -9256.273188, best rearrangement setting 8
Bootstrap[86]: Time 0.052632 seconds, bootstrap likelihood -9325.404433, best rearrangement setting 7
Bootstrap[87]: Time 0.053314 seconds, bootstrap likelihood -9382.823259, best rearrangement setting 7
Bootstrap[88]: Time 0.107846 seconds, bootstrap likelihood -8801.862855, best rearrangement setting 12
Bootstrap[89]: Time 0.138810 seconds, bootstrap likelihood -9373.834914, best rearrangement setting 10
Bootstrap[90]: Time 0.196944 seconds, bootstrap likelihood -8859.258083, best rearrangement setting 8
Bootstrap[91]: Time 0.155251 seconds, bootstrap likelihood -9038.410473, best rearrangement setting 12
Bootstrap[92]: Time 0.134129 seconds, bootstrap likelihood -9131.308538, best rearrangement setting 13
Bootstrap[93]: Time 0.147985 seconds, bootstrap likelihood -9028.621498, best rearrangement setting 15
Bootstrap[94]: Time 0.120174 seconds, bootstrap likelihood -9313.873224, best rearrangement setting 5
Bootstrap[95]: Time 0.126302 seconds, bootstrap likelihood -9406.565639, best rearrangement setting 5
Bootstrap[96]: Time 0.129203 seconds, bootstrap likelihood -9025.328800, best rearrangement setting 13
Bootstrap[97]: Time 0.126753 seconds, bootstrap likelihood -8909.696772, best rearrangement setting 11
Bootstrap[98]: Time 0.124376 seconds, bootstrap likelihood -9160.335854, best rearrangement setting 6
Bootstrap[99]: Time 0.136147 seconds, bootstrap likelihood -9278.663557, best rearrangement setting 14


Stopped Rapid BS search after 100 replicates with MRE-based Bootstopping criterion
WRF Average of 100 random splits: 1.700000 %
Overall Time for 100 Rapid Bootstraps 12.203677 seconds
Average Time per Rapid Bootstrap 0.122037 seconds

Starting ML Search ...

Fast ML optimization finished

Fast ML search Time: 5.920390 seconds

Slow ML Search 0 Likelihood: -9181.783961
Slow ML Search 1 Likelihood: -9181.783961
Slow ML Search 2 Likelihood: -9181.783961
Slow ML Search 3 Likelihood: -9181.783961
Slow ML Search 4 Likelihood: -9181.783961
Slow ML Search 5 Likelihood: -9181.783961
Slow ML Search 6 Likelihood: -9181.783961
Slow ML Search 7 Likelihood: -9181.783961
Slow ML Search 8 Likelihood: -9181.783961
Slow ML Search 9 Likelihood: -9181.783961
Slow ML optimization finished

Slow ML search Time: 2.932964 seconds
Thorough ML search Time: 0.269711 seconds

Final ML Optimization Likelihood: -9181.782079

Model Information:

Model Parameters of Partition 0, Name: No Name Provided, Type of Data: DNA
alpha: 0.330443
Tree-Length: 2.001914
rate A <-> C: 0.568818
rate A <-> G: 1.534358
rate A <-> T: 1.013099
rate C <-> G: 0.698360
rate C <-> T: 3.148489
rate G <-> T: 1.000000

freq pi(A): 0.244633
freq pi(C): 0.232122
freq pi(G): 0.320732
freq pi(T): 0.202513


ML search took 9.171196 secs or 0.002548 hours

Combined Bootstrap and ML search took 21.379676 secs or 0.005939 hours

Drawing Bootstrap Support Values on best-scoring ML tree ...



Found 1 tree in File /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bestTree.KBS.ML



Found 1 tree in File /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bestTree.KBS.ML

Program execution info written to /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_info.KBS.ML
All 100 bootstrapped trees written to: /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bootstrap.KBS.ML

Best-scoring ML tree written to: /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bestTree.KBS.ML

Best-scoring ML tree with support values written to: /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bipartitions.KBS.ML

Best-scoring ML tree with support values as branch labels written to: /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bipartitionsBranchLabels.KBS.ML

Overall execution time for full ML analysis: 21.406092 secs or 0.005946 hours or 0.000248 days

