IMPORTANT WARNING: Alignment column 17 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 18 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 20 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 23 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 25 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 27 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 32 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 33 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 35 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 38 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 40 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 42 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 44 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 45 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 47 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 95 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 96 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 97 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 106 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 142 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 145 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 163 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 167 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 168 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 179 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 309 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 310 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 314 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 571 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 581 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 607 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 608 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 609 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 610 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 622 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 623 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 749 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 770 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 903 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 970 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 977 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1074 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1130 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1131 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1138 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1144 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1145 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1169 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1192 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1251 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1252 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1301 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1675 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1676 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1677 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1678 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1679 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1680 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1681 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1682 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1683 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1684 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1685 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1686 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1687 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1688 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1689 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1690 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1691 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1692 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1693 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1694 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1695 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1696 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1697 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1698 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1699 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1700 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1701 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1702 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1703 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1704 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1705 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1706 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1707 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1708 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1709 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1710 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1711 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1712 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1713 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1749 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1764 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1766 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1769 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1770 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1771 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1772 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1773 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1774 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1775 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1776 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1777 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1778 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1779 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1780 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1781 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1782 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1783 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1784 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1785 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1786 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1787 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1788 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1789 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1790 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1791 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1792 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1793 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1794 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1798 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1799 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1801 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1802 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1805 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1808 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1813 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1816 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1818 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1819 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1821 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1828 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1829 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1830 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1831 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1832 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1835 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1838 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1858 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1859 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1861 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1862 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1863 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1864 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1865 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1866 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1867 contains only undetermined values which will be treated as missing data

IMPORTANT WARNING
Found 147 columns that contain only undetermined values which will be treated as missing data.
Normally these columns should be excluded from the analysis.

Just in case you might need it, an alignment file with 
undetermined columns removed is printed to file ./20170630_KBS.reduced


Using BFGS method to optimize GTR rate parameters, to disable this specify "--no-bfgs" 



This is RAxML version 8.1.3 released by Alexandros Stamatakis on August 13 2014.

With greatly appreciated code contributions by:
Andre Aberer      (HITS)
Simon Berger      (HITS)
Alexey Kozlov     (HITS)
Kassian Kobert    (HITS)
David Dao         (KIT and HITS)
Nick Pattengale   (Sandia)
Wayne Pfeiffer    (SDSC)
Akifumi S. Tanabe (NRIFS)

Alignment has 918 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 29.41%

RAxML rapid bootstrapping and subsequent ML search

Using 1 distinct models/data partitions with joint branch length optimization



Executing 1000 rapid bootstrap inferences and thereafter a thorough ML search 

All free model parameters will be estimated by RAxML
GAMMA model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 918
Name: No Name Provided
DataType: DNA
Substitution Matrix: GTR




RAxML was called as follows:

raxmlHPC-PTHREADS -T 4 -f a -m GTRGAMMA -p 12345 -x 12345 -o Methanosarcina -# autoMRE -s ./20170630_KBS -n KBS.ML 



Time for BS model parameter optimization 0.052899
Bootstrap[0]: Time 0.297508 seconds, bootstrap likelihood -10265.960421, best rearrangement setting 13
Bootstrap[1]: Time 0.249682 seconds, bootstrap likelihood -10414.202188, best rearrangement setting 13
Bootstrap[2]: Time 0.228976 seconds, bootstrap likelihood -10361.475182, best rearrangement setting 12
Bootstrap[3]: Time 0.249575 seconds, bootstrap likelihood -10608.906664, best rearrangement setting 15
Bootstrap[4]: Time 0.105280 seconds, bootstrap likelihood -10292.361602, best rearrangement setting 10
Bootstrap[5]: Time 0.109940 seconds, bootstrap likelihood -10358.141697, best rearrangement setting 10
Bootstrap[6]: Time 0.269327 seconds, bootstrap likelihood -10331.575732, best rearrangement setting 6
Bootstrap[7]: Time 0.250107 seconds, bootstrap likelihood -10055.291413, best rearrangement setting 14
Bootstrap[8]: Time 0.102612 seconds, bootstrap likelihood -10024.330715, best rearrangement setting 5
Bootstrap[9]: Time 0.109550 seconds, bootstrap likelihood -10253.481098, best rearrangement setting 7
Bootstrap[10]: Time 0.237706 seconds, bootstrap likelihood -9982.492760, best rearrangement setting 7
Bootstrap[11]: Time 0.243945 seconds, bootstrap likelihood -10202.429651, best rearrangement setting 5
Bootstrap[12]: Time 0.108122 seconds, bootstrap likelihood -10383.018119, best rearrangement setting 8
Bootstrap[13]: Time 0.102914 seconds, bootstrap likelihood -10213.803363, best rearrangement setting 7
Bootstrap[14]: Time 0.232801 seconds, bootstrap likelihood -10410.730157, best rearrangement setting 12
Bootstrap[15]: Time 0.101938 seconds, bootstrap likelihood -10308.103732, best rearrangement setting 15
Bootstrap[16]: Time 0.116833 seconds, bootstrap likelihood -10440.600355, best rearrangement setting 12
Bootstrap[17]: Time 0.244894 seconds, bootstrap likelihood -10342.745071, best rearrangement setting 12
Bootstrap[18]: Time 0.282458 seconds, bootstrap likelihood -10313.585832, best rearrangement setting 5
Bootstrap[19]: Time 0.240105 seconds, bootstrap likelihood -10400.759313, best rearrangement setting 8
Bootstrap[20]: Time 0.241062 seconds, bootstrap likelihood -10345.619895, best rearrangement setting 10
Bootstrap[21]: Time 0.250747 seconds, bootstrap likelihood -10465.187153, best rearrangement setting 6
Bootstrap[22]: Time 0.108860 seconds, bootstrap likelihood -10272.386104, best rearrangement setting 5
Bootstrap[23]: Time 0.227883 seconds, bootstrap likelihood -10309.062218, best rearrangement setting 7
Bootstrap[24]: Time 0.240352 seconds, bootstrap likelihood -10396.071670, best rearrangement setting 8
Bootstrap[25]: Time 0.109461 seconds, bootstrap likelihood -10138.717504, best rearrangement setting 6
Bootstrap[26]: Time 0.257257 seconds, bootstrap likelihood -9937.348261, best rearrangement setting 12
Bootstrap[27]: Time 0.243176 seconds, bootstrap likelihood -10296.937025, best rearrangement setting 10
Bootstrap[28]: Time 0.244984 seconds, bootstrap likelihood -10404.463436, best rearrangement setting 11
Bootstrap[29]: Time 0.296447 seconds, bootstrap likelihood -10459.041183, best rearrangement setting 12
Bootstrap[30]: Time 0.118242 seconds, bootstrap likelihood -10358.872908, best rearrangement setting 15
Bootstrap[31]: Time 0.216179 seconds, bootstrap likelihood -10253.614719, best rearrangement setting 15
Bootstrap[32]: Time 0.242579 seconds, bootstrap likelihood -10147.094176, best rearrangement setting 6
Bootstrap[33]: Time 0.259106 seconds, bootstrap likelihood -10304.911863, best rearrangement setting 15
Bootstrap[34]: Time 0.280391 seconds, bootstrap likelihood -10415.016944, best rearrangement setting 11
Bootstrap[35]: Time 0.266578 seconds, bootstrap likelihood -10435.605055, best rearrangement setting 8
Bootstrap[36]: Time 0.265883 seconds, bootstrap likelihood -10164.543533, best rearrangement setting 9
Bootstrap[37]: Time 0.281928 seconds, bootstrap likelihood -10567.907465, best rearrangement setting 11
Bootstrap[38]: Time 0.246805 seconds, bootstrap likelihood -10243.035504, best rearrangement setting 8
Bootstrap[39]: Time 0.274115 seconds, bootstrap likelihood -10330.807470, best rearrangement setting 13
Bootstrap[40]: Time 0.112176 seconds, bootstrap likelihood -10475.383428, best rearrangement setting 13
Bootstrap[41]: Time 0.123708 seconds, bootstrap likelihood -10446.496806, best rearrangement setting 10
Bootstrap[42]: Time 0.266233 seconds, bootstrap likelihood -10316.820239, best rearrangement setting 5
Bootstrap[43]: Time 0.252840 seconds, bootstrap likelihood -10339.815054, best rearrangement setting 14
Bootstrap[44]: Time 0.108595 seconds, bootstrap likelihood -10128.948966, best rearrangement setting 10
Bootstrap[45]: Time 0.231615 seconds, bootstrap likelihood -10162.092389, best rearrangement setting 15
Bootstrap[46]: Time 0.217563 seconds, bootstrap likelihood -9814.264927, best rearrangement setting 14
Bootstrap[47]: Time 0.235012 seconds, bootstrap likelihood -10356.568422, best rearrangement setting 8
Bootstrap[48]: Time 0.253622 seconds, bootstrap likelihood -10384.348143, best rearrangement setting 6
Bootstrap[49]: Time 0.268564 seconds, bootstrap likelihood -10107.426864, best rearrangement setting 7
Bootstrap[50]: Time 0.118626 seconds, bootstrap likelihood -10045.661645, best rearrangement setting 7
Bootstrap[51]: Time 0.110942 seconds, bootstrap likelihood -10370.339908, best rearrangement setting 11
Bootstrap[52]: Time 0.252275 seconds, bootstrap likelihood -10172.933590, best rearrangement setting 12
Bootstrap[53]: Time 0.277222 seconds, bootstrap likelihood -9916.287364, best rearrangement setting 8
Bootstrap[54]: Time 0.256306 seconds, bootstrap likelihood -10272.006007, best rearrangement setting 9
Bootstrap[55]: Time 0.260585 seconds, bootstrap likelihood -10259.596435, best rearrangement setting 11
Bootstrap[56]: Time 0.237426 seconds, bootstrap likelihood -10322.973887, best rearrangement setting 5
Bootstrap[57]: Time 0.277172 seconds, bootstrap likelihood -10373.357012, best rearrangement setting 7
Bootstrap[58]: Time 0.117732 seconds, bootstrap likelihood -10679.012298, best rearrangement setting 10
Bootstrap[59]: Time 0.245442 seconds, bootstrap likelihood -10328.250746, best rearrangement setting 9
Bootstrap[60]: Time 0.241471 seconds, bootstrap likelihood -10481.690797, best rearrangement setting 7
Bootstrap[61]: Time 0.241809 seconds, bootstrap likelihood -10307.553295, best rearrangement setting 5
Bootstrap[62]: Time 0.229178 seconds, bootstrap likelihood -10007.850301, best rearrangement setting 11
Bootstrap[63]: Time 0.301282 seconds, bootstrap likelihood -10385.597758, best rearrangement setting 12
Bootstrap[64]: Time 0.247191 seconds, bootstrap likelihood -10234.208161, best rearrangement setting 7
Bootstrap[65]: Time 0.235495 seconds, bootstrap likelihood -10064.957850, best rearrangement setting 5
Bootstrap[66]: Time 0.106200 seconds, bootstrap likelihood -10568.025082, best rearrangement setting 5
Bootstrap[67]: Time 0.244322 seconds, bootstrap likelihood -10184.394835, best rearrangement setting 15
Bootstrap[68]: Time 0.247766 seconds, bootstrap likelihood -10415.309641, best rearrangement setting 11
Bootstrap[69]: Time 0.244193 seconds, bootstrap likelihood -9756.322551, best rearrangement setting 5
Bootstrap[70]: Time 0.108972 seconds, bootstrap likelihood -10333.635456, best rearrangement setting 8
Bootstrap[71]: Time 0.248599 seconds, bootstrap likelihood -10290.906136, best rearrangement setting 10
Bootstrap[72]: Time 0.262738 seconds, bootstrap likelihood -10186.153564, best rearrangement setting 11
Bootstrap[73]: Time 0.233252 seconds, bootstrap likelihood -10274.176854, best rearrangement setting 9
Bootstrap[74]: Time 0.216133 seconds, bootstrap likelihood -9981.261971, best rearrangement setting 5
Bootstrap[75]: Time 0.232495 seconds, bootstrap likelihood -10399.798418, best rearrangement setting 8
Bootstrap[76]: Time 0.225968 seconds, bootstrap likelihood -10342.965271, best rearrangement setting 9
Bootstrap[77]: Time 0.236747 seconds, bootstrap likelihood -10173.810948, best rearrangement setting 11
Bootstrap[78]: Time 0.254185 seconds, bootstrap likelihood -10000.316212, best rearrangement setting 15
Bootstrap[79]: Time 0.269931 seconds, bootstrap likelihood -10125.371814, best rearrangement setting 9
Bootstrap[80]: Time 0.234526 seconds, bootstrap likelihood -10598.646488, best rearrangement setting 15
Bootstrap[81]: Time 0.251013 seconds, bootstrap likelihood -10598.376378, best rearrangement setting 7
Bootstrap[82]: Time 0.233223 seconds, bootstrap likelihood -10292.512035, best rearrangement setting 6
Bootstrap[83]: Time 0.101860 seconds, bootstrap likelihood -10087.023498, best rearrangement setting 10
Bootstrap[84]: Time 0.243425 seconds, bootstrap likelihood -10077.373051, best rearrangement setting 11
Bootstrap[85]: Time 0.228622 seconds, bootstrap likelihood -10191.907599, best rearrangement setting 8
Bootstrap[86]: Time 0.236251 seconds, bootstrap likelihood -10190.263264, best rearrangement setting 7
Bootstrap[87]: Time 0.110719 seconds, bootstrap likelihood -10415.516616, best rearrangement setting 7
Bootstrap[88]: Time 0.233851 seconds, bootstrap likelihood -10352.997457, best rearrangement setting 12
Bootstrap[89]: Time 0.235778 seconds, bootstrap likelihood -10394.687381, best rearrangement setting 10
Bootstrap[90]: Time 0.238477 seconds, bootstrap likelihood -10426.248245, best rearrangement setting 8
Bootstrap[91]: Time 0.251763 seconds, bootstrap likelihood -10162.369966, best rearrangement setting 12
Bootstrap[92]: Time 0.231694 seconds, bootstrap likelihood -10339.599915, best rearrangement setting 13
Bootstrap[93]: Time 0.246596 seconds, bootstrap likelihood -10075.596906, best rearrangement setting 15
Bootstrap[94]: Time 0.281662 seconds, bootstrap likelihood -10387.910117, best rearrangement setting 5
Bootstrap[95]: Time 0.243050 seconds, bootstrap likelihood -10332.253996, best rearrangement setting 5
Bootstrap[96]: Time 0.112056 seconds, bootstrap likelihood -10544.803388, best rearrangement setting 13
Bootstrap[97]: Time 0.241275 seconds, bootstrap likelihood -10562.674210, best rearrangement setting 11
Bootstrap[98]: Time 0.248582 seconds, bootstrap likelihood -10127.174102, best rearrangement setting 6
Bootstrap[99]: Time 0.229876 seconds, bootstrap likelihood -10236.597990, best rearrangement setting 14
Bootstrap[100]: Time 0.243357 seconds, bootstrap likelihood -10050.861931, best rearrangement setting 12
Bootstrap[101]: Time 0.246268 seconds, bootstrap likelihood -9985.778552, best rearrangement setting 10
Bootstrap[102]: Time 0.252963 seconds, bootstrap likelihood -10256.959363, best rearrangement setting 8
Bootstrap[103]: Time 0.233213 seconds, bootstrap likelihood -9904.943130, best rearrangement setting 8
Bootstrap[104]: Time 0.118883 seconds, bootstrap likelihood -10383.557782, best rearrangement setting 15
Bootstrap[105]: Time 0.109493 seconds, bootstrap likelihood -9883.292636, best rearrangement setting 7
Bootstrap[106]: Time 0.265859 seconds, bootstrap likelihood -10104.609922, best rearrangement setting 6
Bootstrap[107]: Time 0.241073 seconds, bootstrap likelihood -10267.984608, best rearrangement setting 13
Bootstrap[108]: Time 0.223789 seconds, bootstrap likelihood -10227.144502, best rearrangement setting 14
Bootstrap[109]: Time 0.245701 seconds, bootstrap likelihood -10261.676249, best rearrangement setting 12
Bootstrap[110]: Time 0.256824 seconds, bootstrap likelihood -10368.658313, best rearrangement setting 7
Bootstrap[111]: Time 0.237629 seconds, bootstrap likelihood -10296.970009, best rearrangement setting 15
Bootstrap[112]: Time 0.224035 seconds, bootstrap likelihood -10027.023521, best rearrangement setting 14
Bootstrap[113]: Time 0.230104 seconds, bootstrap likelihood -10450.463052, best rearrangement setting 5
Bootstrap[114]: Time 0.246615 seconds, bootstrap likelihood -10375.666439, best rearrangement setting 6
Bootstrap[115]: Time 0.262880 seconds, bootstrap likelihood -10188.135613, best rearrangement setting 7
Bootstrap[116]: Time 0.244810 seconds, bootstrap likelihood -10094.142370, best rearrangement setting 11
Bootstrap[117]: Time 0.227807 seconds, bootstrap likelihood -10480.229879, best rearrangement setting 8
Bootstrap[118]: Time 0.249179 seconds, bootstrap likelihood -9981.842348, best rearrangement setting 9
Bootstrap[119]: Time 0.105399 seconds, bootstrap likelihood -10254.633403, best rearrangement setting 14
Bootstrap[120]: Time 0.112083 seconds, bootstrap likelihood -10453.258473, best rearrangement setting 12
Bootstrap[121]: Time 0.225519 seconds, bootstrap likelihood -10138.050420, best rearrangement setting 8
Bootstrap[122]: Time 0.237083 seconds, bootstrap likelihood -10257.068831, best rearrangement setting 9
Bootstrap[123]: Time 0.235657 seconds, bootstrap likelihood -10178.424861, best rearrangement setting 6
Bootstrap[124]: Time 0.112513 seconds, bootstrap likelihood -10098.377062, best rearrangement setting 11
Bootstrap[125]: Time 0.261091 seconds, bootstrap likelihood -10461.385618, best rearrangement setting 11
Bootstrap[126]: Time 0.254398 seconds, bootstrap likelihood -10194.175023, best rearrangement setting 12
Bootstrap[127]: Time 0.233592 seconds, bootstrap likelihood -10305.603225, best rearrangement setting 9
Bootstrap[128]: Time 0.251516 seconds, bootstrap likelihood -10632.283087, best rearrangement setting 11
Bootstrap[129]: Time 0.242841 seconds, bootstrap likelihood -10378.181166, best rearrangement setting 5
Bootstrap[130]: Time 0.245647 seconds, bootstrap likelihood -10058.001041, best rearrangement setting 10
Bootstrap[131]: Time 0.260925 seconds, bootstrap likelihood -10486.613751, best rearrangement setting 9
Bootstrap[132]: Time 0.232538 seconds, bootstrap likelihood -10418.111217, best rearrangement setting 14
Bootstrap[133]: Time 0.238420 seconds, bootstrap likelihood -10342.585977, best rearrangement setting 13
Bootstrap[134]: Time 0.113842 seconds, bootstrap likelihood -10481.574209, best rearrangement setting 6
Bootstrap[135]: Time 0.251283 seconds, bootstrap likelihood -10196.672232, best rearrangement setting 11
Bootstrap[136]: Time 0.230143 seconds, bootstrap likelihood -9947.733148, best rearrangement setting 13
Bootstrap[137]: Time 0.223910 seconds, bootstrap likelihood -10598.170233, best rearrangement setting 6
Bootstrap[138]: Time 0.239669 seconds, bootstrap likelihood -10388.913391, best rearrangement setting 15
Bootstrap[139]: Time 0.113219 seconds, bootstrap likelihood -10337.098021, best rearrangement setting 5
Bootstrap[140]: Time 0.250670 seconds, bootstrap likelihood -10451.551848, best rearrangement setting 13
Bootstrap[141]: Time 0.113426 seconds, bootstrap likelihood -10082.796929, best rearrangement setting 5
Bootstrap[142]: Time 0.113368 seconds, bootstrap likelihood -10410.859554, best rearrangement setting 15
Bootstrap[143]: Time 0.112004 seconds, bootstrap likelihood -10375.778035, best rearrangement setting 7
Bootstrap[144]: Time 0.241987 seconds, bootstrap likelihood -10336.374538, best rearrangement setting 13
Bootstrap[145]: Time 0.220446 seconds, bootstrap likelihood -9992.883503, best rearrangement setting 7
Bootstrap[146]: Time 0.260463 seconds, bootstrap likelihood -10608.081328, best rearrangement setting 9
Bootstrap[147]: Time 0.254205 seconds, bootstrap likelihood -10550.258603, best rearrangement setting 12
Bootstrap[148]: Time 0.251247 seconds, bootstrap likelihood -10363.915057, best rearrangement setting 8
Bootstrap[149]: Time 0.237928 seconds, bootstrap likelihood -10262.289805, best rearrangement setting 12


Stopped Rapid BS search after 150 replicates with MRE-based Bootstopping criterion
WRF Average of 100 random splits: 1.740000
Overall Time for 150 Rapid Bootstraps 33.092737 seconds
Average Time per Rapid Bootstrap 0.220618 seconds

Starting ML Search ...

Fast ML optimization finished

Fast ML search Time: 17.848219 seconds

Slow ML Search 0 Likelihood: -10283.011042
Slow ML Search 1 Likelihood: -10283.011042
Slow ML Search 2 Likelihood: -10283.011042
Slow ML Search 3 Likelihood: -10283.011042
Slow ML Search 4 Likelihood: -10283.011042
Slow ML Search 5 Likelihood: -10283.011042
Slow ML Search 6 Likelihood: -10283.011042
Slow ML Search 7 Likelihood: -10283.011042
Slow ML Search 8 Likelihood: -10283.011042
Slow ML Search 9 Likelihood: -10283.011042
Slow ML optimization finished

Slow ML search Time: 5.111937 seconds
Thorough ML search Time: 0.507240 seconds

Final ML Optimization Likelihood: -10283.011044

Model Information:

Model Parameters of Partition 0, Name: No Name Provided, Type of Data: DNA
alpha: 0.559432
Tree-Length: 3.296122
rate A <-> C: 0.358487
rate A <-> G: 0.443939
rate A <-> T: 0.498208
rate C <-> G: 0.221099
rate C <-> T: 2.088568
rate G <-> T: 1.000000

freq pi(A): 0.241498
freq pi(C): 0.233799
freq pi(G): 0.324035
freq pi(T): 0.200668


ML search took 23.492998 secs or 0.006526 hours

Combined Bootstrap and ML search took 56.587736 secs or 0.015719 hours

Drawing Bootstrap Support Values on best-scoring ML tree ...



Found 1 tree in File /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bestTree.KBS.ML



Found 1 tree in File /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bestTree.KBS.ML

Program execution info written to /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_info.KBS.ML
All 150 bootstrapped trees written to: /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bootstrap.KBS.ML

Best-scoring ML tree written to: /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bestTree.KBS.ML

Best-scoring ML tree with support values written to: /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bipartitions.KBS.ML

Best-scoring ML tree with support values as branch labels written to: /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bipartitionsBranchLabels.KBS.ML

Overall execution time for full ML analysis: 56.605404 secs or 0.015724 hours or 0.000655 days

