IMPORTANT WARNING: Alignment column 17 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 18 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 20 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 23 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 25 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 27 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 32 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 33 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 35 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 38 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 40 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 42 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 44 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 45 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 47 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 95 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 96 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 97 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 106 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 142 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 145 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 163 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 167 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 168 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 179 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 309 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 310 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 314 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 571 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 581 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 607 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 608 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 609 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 610 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 622 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 623 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 749 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 770 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 903 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 970 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 977 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1074 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1130 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1131 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1138 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1144 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1145 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1169 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1192 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1251 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1252 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1301 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1675 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1676 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1677 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1678 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1679 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1680 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1681 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1682 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1683 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1684 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1685 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1686 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1687 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1688 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1689 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1690 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1691 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1692 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1693 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1694 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1695 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1696 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1697 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1698 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1699 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1700 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1701 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1702 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1703 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1704 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1705 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1706 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1707 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1708 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1709 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1710 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1711 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1712 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1713 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1749 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1764 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1766 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1769 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1770 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1771 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1772 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1773 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1774 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1775 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1776 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1777 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1778 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1779 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1780 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1781 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1782 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1783 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1784 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1785 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1786 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1787 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1788 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1789 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1790 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1791 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1792 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1793 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1794 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1798 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1799 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1801 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1802 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1805 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1808 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1813 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1816 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1818 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1819 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1821 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1828 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1829 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1830 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1831 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1832 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1835 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1838 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1858 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1859 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1861 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1862 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1863 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1864 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1865 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1866 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1867 contains only undetermined values which will be treated as missing data

IMPORTANT WARNING
Found 147 columns that contain only undetermined values which will be treated as missing data.
Normally these columns should be excluded from the analysis.

An alignment file with undetermined columns removed has already
been printed to file ./20180405_KBS.reduced


Using BFGS method to optimize GTR rate parameters, to disable this specify "--no-bfgs" 


Alignment has 147 completely undetermined sites that will be automatically removed from the input data



This is RAxML version 8.2.11 released by Alexandros Stamatakis on June 2017.

With greatly appreciated code contributions by:
Andre Aberer      (HITS)
Simon Berger      (HITS)
Alexey Kozlov     (HITS)
Kassian Kobert    (HITS)
David Dao         (KIT and HITS)
Sarah Lutteropp   (KIT and HITS)
Nick Pattengale   (Sandia)
Wayne Pfeiffer    (SDSC)
Akifumi S. Tanabe (NRIFS)
Charlie Taylor    (UF)


Alignment has 911 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 30.29%

RAxML rapid bootstrapping and subsequent ML search

Using 1 distinct models/data partitions with joint branch length optimization



Executing 1000 rapid bootstrap inferences and thereafter a thorough ML search 

All free model parameters will be estimated by RAxML
GAMMA model of rate heterogeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 911
Name: No Name Provided
DataType: DNA
Substitution Matrix: GTR




RAxML was called as follows:

raxmlHPC-PTHREADS -T 4 -f a -m GTRGAMMA -p 12345 -x 12345 -o Methanosarcina -# autoMRE -s ./20180405_KBS -n KBS.ML 



Time for BS model parameter optimization 0.088582
Bootstrap[0]: Time 0.203000 seconds, bootstrap likelihood -10091.347245, best rearrangement setting 13
Bootstrap[1]: Time 0.173894 seconds, bootstrap likelihood -9841.569795, best rearrangement setting 13
Bootstrap[2]: Time 0.168080 seconds, bootstrap likelihood -9812.394266, best rearrangement setting 12
Bootstrap[3]: Time 0.160793 seconds, bootstrap likelihood -10003.628087, best rearrangement setting 15
Bootstrap[4]: Time 0.169969 seconds, bootstrap likelihood -10007.361267, best rearrangement setting 10
Bootstrap[5]: Time 0.073921 seconds, bootstrap likelihood -10102.581668, best rearrangement setting 10
Bootstrap[6]: Time 0.155298 seconds, bootstrap likelihood -10145.802883, best rearrangement setting 6
Bootstrap[7]: Time 0.161348 seconds, bootstrap likelihood -10280.770736, best rearrangement setting 14
Bootstrap[8]: Time 0.161732 seconds, bootstrap likelihood -9830.279562, best rearrangement setting 5
Bootstrap[9]: Time 0.077113 seconds, bootstrap likelihood -10161.244954, best rearrangement setting 7
Bootstrap[10]: Time 0.164870 seconds, bootstrap likelihood -9924.603476, best rearrangement setting 7
Bootstrap[11]: Time 0.149099 seconds, bootstrap likelihood -10067.809303, best rearrangement setting 5
Bootstrap[12]: Time 0.145724 seconds, bootstrap likelihood -9937.870741, best rearrangement setting 8
Bootstrap[13]: Time 0.157667 seconds, bootstrap likelihood -10123.152134, best rearrangement setting 7
Bootstrap[14]: Time 0.150280 seconds, bootstrap likelihood -9913.575373, best rearrangement setting 12
Bootstrap[15]: Time 0.070611 seconds, bootstrap likelihood -10197.510788, best rearrangement setting 15
Bootstrap[16]: Time 0.146661 seconds, bootstrap likelihood -9868.205257, best rearrangement setting 12
Bootstrap[17]: Time 0.145216 seconds, bootstrap likelihood -9887.868472, best rearrangement setting 12
Bootstrap[18]: Time 0.155948 seconds, bootstrap likelihood -9847.538966, best rearrangement setting 5
Bootstrap[19]: Time 0.141013 seconds, bootstrap likelihood -10170.415382, best rearrangement setting 8
Bootstrap[20]: Time 0.162370 seconds, bootstrap likelihood -9770.419190, best rearrangement setting 10
Bootstrap[21]: Time 0.145223 seconds, bootstrap likelihood -10032.733377, best rearrangement setting 6
Bootstrap[22]: Time 0.144265 seconds, bootstrap likelihood -9862.078573, best rearrangement setting 5
Bootstrap[23]: Time 0.145804 seconds, bootstrap likelihood -9917.618604, best rearrangement setting 7
Bootstrap[24]: Time 0.142394 seconds, bootstrap likelihood -10289.570266, best rearrangement setting 8
Bootstrap[25]: Time 0.155676 seconds, bootstrap likelihood -10031.959875, best rearrangement setting 6
Bootstrap[26]: Time 0.152668 seconds, bootstrap likelihood -10063.660563, best rearrangement setting 12
Bootstrap[27]: Time 0.160129 seconds, bootstrap likelihood -9947.656957, best rearrangement setting 10
Bootstrap[28]: Time 0.149739 seconds, bootstrap likelihood -10098.991036, best rearrangement setting 11
Bootstrap[29]: Time 0.160967 seconds, bootstrap likelihood -10137.067458, best rearrangement setting 12
Bootstrap[30]: Time 0.067278 seconds, bootstrap likelihood -9956.008550, best rearrangement setting 15
Bootstrap[31]: Time 0.148594 seconds, bootstrap likelihood -10289.698968, best rearrangement setting 15
Bootstrap[32]: Time 0.064588 seconds, bootstrap likelihood -10167.596661, best rearrangement setting 6
Bootstrap[33]: Time 0.143666 seconds, bootstrap likelihood -9590.884487, best rearrangement setting 15
Bootstrap[34]: Time 0.147446 seconds, bootstrap likelihood -9777.345843, best rearrangement setting 11
Bootstrap[35]: Time 0.163933 seconds, bootstrap likelihood -10062.708853, best rearrangement setting 8
Bootstrap[36]: Time 0.146142 seconds, bootstrap likelihood -10051.620731, best rearrangement setting 9
Bootstrap[37]: Time 0.144847 seconds, bootstrap likelihood -10072.778344, best rearrangement setting 11
Bootstrap[38]: Time 0.141387 seconds, bootstrap likelihood -10056.517594, best rearrangement setting 8
Bootstrap[39]: Time 0.149968 seconds, bootstrap likelihood -9869.891507, best rearrangement setting 13
Bootstrap[40]: Time 0.150394 seconds, bootstrap likelihood -9915.350950, best rearrangement setting 13
Bootstrap[41]: Time 0.147799 seconds, bootstrap likelihood -10116.597725, best rearrangement setting 10
Bootstrap[42]: Time 0.154438 seconds, bootstrap likelihood -9845.542845, best rearrangement setting 5
Bootstrap[43]: Time 0.146084 seconds, bootstrap likelihood -9681.448379, best rearrangement setting 14
Bootstrap[44]: Time 0.069999 seconds, bootstrap likelihood -10001.471857, best rearrangement setting 10
Bootstrap[45]: Time 0.148865 seconds, bootstrap likelihood -10124.715002, best rearrangement setting 15
Bootstrap[46]: Time 0.147268 seconds, bootstrap likelihood -9896.605547, best rearrangement setting 14
Bootstrap[47]: Time 0.159716 seconds, bootstrap likelihood -10031.837546, best rearrangement setting 8
Bootstrap[48]: Time 0.159201 seconds, bootstrap likelihood -9995.672212, best rearrangement setting 6
Bootstrap[49]: Time 0.150704 seconds, bootstrap likelihood -9896.495783, best rearrangement setting 7
Bootstrap[50]: Time 0.155327 seconds, bootstrap likelihood -10321.035494, best rearrangement setting 7
Bootstrap[51]: Time 0.153764 seconds, bootstrap likelihood -10046.124649, best rearrangement setting 11
Bootstrap[52]: Time 0.141016 seconds, bootstrap likelihood -10211.402018, best rearrangement setting 12
Bootstrap[53]: Time 0.151098 seconds, bootstrap likelihood -9699.801534, best rearrangement setting 8
Bootstrap[54]: Time 0.071491 seconds, bootstrap likelihood -10100.485540, best rearrangement setting 9
Bootstrap[55]: Time 0.069937 seconds, bootstrap likelihood -9914.512382, best rearrangement setting 11
Bootstrap[56]: Time 0.158969 seconds, bootstrap likelihood -9942.835242, best rearrangement setting 5
Bootstrap[57]: Time 0.145938 seconds, bootstrap likelihood -10131.889208, best rearrangement setting 7
Bootstrap[58]: Time 0.148111 seconds, bootstrap likelihood -9742.094234, best rearrangement setting 10
Bootstrap[59]: Time 0.153468 seconds, bootstrap likelihood -10178.170019, best rearrangement setting 9
Bootstrap[60]: Time 0.068181 seconds, bootstrap likelihood -10061.293915, best rearrangement setting 7
Bootstrap[61]: Time 0.147560 seconds, bootstrap likelihood -10036.731886, best rearrangement setting 5
Bootstrap[62]: Time 0.138346 seconds, bootstrap likelihood -9807.389358, best rearrangement setting 11
Bootstrap[63]: Time 0.153340 seconds, bootstrap likelihood -9835.947033, best rearrangement setting 12
Bootstrap[64]: Time 0.149722 seconds, bootstrap likelihood -9927.717420, best rearrangement setting 7
Bootstrap[65]: Time 0.158721 seconds, bootstrap likelihood -10206.798140, best rearrangement setting 5
Bootstrap[66]: Time 0.070321 seconds, bootstrap likelihood -10158.893025, best rearrangement setting 5
Bootstrap[67]: Time 0.150206 seconds, bootstrap likelihood -9954.970600, best rearrangement setting 15
Bootstrap[68]: Time 0.142739 seconds, bootstrap likelihood -9798.865253, best rearrangement setting 11
Bootstrap[69]: Time 0.070307 seconds, bootstrap likelihood -9931.038658, best rearrangement setting 5
Bootstrap[70]: Time 0.074680 seconds, bootstrap likelihood -10066.180315, best rearrangement setting 8
Bootstrap[71]: Time 0.157048 seconds, bootstrap likelihood -9753.918215, best rearrangement setting 10
Bootstrap[72]: Time 0.140576 seconds, bootstrap likelihood -9979.452541, best rearrangement setting 11
Bootstrap[73]: Time 0.145662 seconds, bootstrap likelihood -10137.225602, best rearrangement setting 9
Bootstrap[74]: Time 0.155285 seconds, bootstrap likelihood -9996.161246, best rearrangement setting 5
Bootstrap[75]: Time 0.163691 seconds, bootstrap likelihood -10000.117830, best rearrangement setting 8
Bootstrap[76]: Time 0.158038 seconds, bootstrap likelihood -10102.313622, best rearrangement setting 9
Bootstrap[77]: Time 0.152388 seconds, bootstrap likelihood -10192.086308, best rearrangement setting 11
Bootstrap[78]: Time 0.150516 seconds, bootstrap likelihood -10143.556476, best rearrangement setting 15
Bootstrap[79]: Time 0.149813 seconds, bootstrap likelihood -9771.082511, best rearrangement setting 9
Bootstrap[80]: Time 0.152134 seconds, bootstrap likelihood -9727.991557, best rearrangement setting 15
Bootstrap[81]: Time 0.153873 seconds, bootstrap likelihood -10072.537922, best rearrangement setting 7
Bootstrap[82]: Time 0.150210 seconds, bootstrap likelihood -9735.251760, best rearrangement setting 6
Bootstrap[83]: Time 0.136602 seconds, bootstrap likelihood -9966.514834, best rearrangement setting 10
Bootstrap[84]: Time 0.149393 seconds, bootstrap likelihood -9962.370307, best rearrangement setting 11
Bootstrap[85]: Time 0.152272 seconds, bootstrap likelihood -10006.539952, best rearrangement setting 8
Bootstrap[86]: Time 0.157574 seconds, bootstrap likelihood -9950.041474, best rearrangement setting 7
Bootstrap[87]: Time 0.157228 seconds, bootstrap likelihood -10062.886993, best rearrangement setting 7
Bootstrap[88]: Time 0.072845 seconds, bootstrap likelihood -10111.418139, best rearrangement setting 12
Bootstrap[89]: Time 0.148345 seconds, bootstrap likelihood -10016.826702, best rearrangement setting 10
Bootstrap[90]: Time 0.144642 seconds, bootstrap likelihood -9905.261583, best rearrangement setting 8
Bootstrap[91]: Time 0.141182 seconds, bootstrap likelihood -10076.829350, best rearrangement setting 12
Bootstrap[92]: Time 0.146494 seconds, bootstrap likelihood -9991.564801, best rearrangement setting 13
Bootstrap[93]: Time 0.161778 seconds, bootstrap likelihood -9825.013772, best rearrangement setting 15
Bootstrap[94]: Time 0.163535 seconds, bootstrap likelihood -10083.538299, best rearrangement setting 5
Bootstrap[95]: Time 0.157873 seconds, bootstrap likelihood -9989.958461, best rearrangement setting 5
Bootstrap[96]: Time 0.154073 seconds, bootstrap likelihood -9987.216534, best rearrangement setting 13
Bootstrap[97]: Time 0.139152 seconds, bootstrap likelihood -10161.290659, best rearrangement setting 11
Bootstrap[98]: Time 0.162810 seconds, bootstrap likelihood -9820.429627, best rearrangement setting 6
Bootstrap[99]: Time 0.074692 seconds, bootstrap likelihood -10044.594254, best rearrangement setting 14
Bootstrap[100]: Time 0.164392 seconds, bootstrap likelihood -10161.383400, best rearrangement setting 12
Bootstrap[101]: Time 0.064590 seconds, bootstrap likelihood -10091.239419, best rearrangement setting 10
Bootstrap[102]: Time 0.071349 seconds, bootstrap likelihood -10258.089246, best rearrangement setting 8
Bootstrap[103]: Time 0.164797 seconds, bootstrap likelihood -10067.424261, best rearrangement setting 8
Bootstrap[104]: Time 0.166314 seconds, bootstrap likelihood -10110.797924, best rearrangement setting 15
Bootstrap[105]: Time 0.068150 seconds, bootstrap likelihood -10374.788868, best rearrangement setting 7
Bootstrap[106]: Time 0.151768 seconds, bootstrap likelihood -9863.171877, best rearrangement setting 6
Bootstrap[107]: Time 0.158454 seconds, bootstrap likelihood -10164.753204, best rearrangement setting 13
Bootstrap[108]: Time 0.144716 seconds, bootstrap likelihood -10121.597598, best rearrangement setting 14
Bootstrap[109]: Time 0.064629 seconds, bootstrap likelihood -10108.388594, best rearrangement setting 12
Bootstrap[110]: Time 0.153799 seconds, bootstrap likelihood -9662.181948, best rearrangement setting 7
Bootstrap[111]: Time 0.151176 seconds, bootstrap likelihood -9928.904679, best rearrangement setting 15
Bootstrap[112]: Time 0.140883 seconds, bootstrap likelihood -9803.259252, best rearrangement setting 14
Bootstrap[113]: Time 0.068832 seconds, bootstrap likelihood -9874.685212, best rearrangement setting 5
Bootstrap[114]: Time 0.152460 seconds, bootstrap likelihood -9827.658881, best rearrangement setting 6
Bootstrap[115]: Time 0.179211 seconds, bootstrap likelihood -9759.889800, best rearrangement setting 7
Bootstrap[116]: Time 0.141364 seconds, bootstrap likelihood -9800.627835, best rearrangement setting 11
Bootstrap[117]: Time 0.149873 seconds, bootstrap likelihood -9811.426077, best rearrangement setting 8
Bootstrap[118]: Time 0.154997 seconds, bootstrap likelihood -10059.214003, best rearrangement setting 9
Bootstrap[119]: Time 0.157855 seconds, bootstrap likelihood -9602.934197, best rearrangement setting 14
Bootstrap[120]: Time 0.150125 seconds, bootstrap likelihood -9972.258541, best rearrangement setting 12
Bootstrap[121]: Time 0.144885 seconds, bootstrap likelihood -10205.690724, best rearrangement setting 8
Bootstrap[122]: Time 0.141906 seconds, bootstrap likelihood -9931.693641, best rearrangement setting 9
Bootstrap[123]: Time 0.154684 seconds, bootstrap likelihood -9894.041483, best rearrangement setting 6
Bootstrap[124]: Time 0.142185 seconds, bootstrap likelihood -10576.624124, best rearrangement setting 11
Bootstrap[125]: Time 0.150623 seconds, bootstrap likelihood -10175.669504, best rearrangement setting 11
Bootstrap[126]: Time 0.146742 seconds, bootstrap likelihood -10109.233982, best rearrangement setting 12
Bootstrap[127]: Time 0.143059 seconds, bootstrap likelihood -9851.531522, best rearrangement setting 9
Bootstrap[128]: Time 0.163984 seconds, bootstrap likelihood -10097.774546, best rearrangement setting 11
Bootstrap[129]: Time 0.065587 seconds, bootstrap likelihood -9877.477251, best rearrangement setting 5
Bootstrap[130]: Time 0.141884 seconds, bootstrap likelihood -10039.761702, best rearrangement setting 10
Bootstrap[131]: Time 0.164828 seconds, bootstrap likelihood -10320.122149, best rearrangement setting 9
Bootstrap[132]: Time 0.148925 seconds, bootstrap likelihood -10186.167615, best rearrangement setting 14
Bootstrap[133]: Time 0.156779 seconds, bootstrap likelihood -9807.533022, best rearrangement setting 13
Bootstrap[134]: Time 0.152762 seconds, bootstrap likelihood -9992.170938, best rearrangement setting 6
Bootstrap[135]: Time 0.150842 seconds, bootstrap likelihood -9791.705686, best rearrangement setting 11
Bootstrap[136]: Time 0.141716 seconds, bootstrap likelihood -9918.487307, best rearrangement setting 13
Bootstrap[137]: Time 0.152060 seconds, bootstrap likelihood -10074.556138, best rearrangement setting 6
Bootstrap[138]: Time 0.156548 seconds, bootstrap likelihood -10152.938615, best rearrangement setting 15
Bootstrap[139]: Time 0.067250 seconds, bootstrap likelihood -10213.079621, best rearrangement setting 5
Bootstrap[140]: Time 0.136616 seconds, bootstrap likelihood -9892.370675, best rearrangement setting 13
Bootstrap[141]: Time 0.155484 seconds, bootstrap likelihood -10046.246440, best rearrangement setting 5
Bootstrap[142]: Time 0.164812 seconds, bootstrap likelihood -9938.798456, best rearrangement setting 15
Bootstrap[143]: Time 0.142317 seconds, bootstrap likelihood -9800.572800, best rearrangement setting 7
Bootstrap[144]: Time 0.153548 seconds, bootstrap likelihood -10054.293376, best rearrangement setting 13
Bootstrap[145]: Time 0.153451 seconds, bootstrap likelihood -10323.234674, best rearrangement setting 7
Bootstrap[146]: Time 0.155599 seconds, bootstrap likelihood -10180.634059, best rearrangement setting 9
Bootstrap[147]: Time 0.147770 seconds, bootstrap likelihood -9916.738734, best rearrangement setting 12
Bootstrap[148]: Time 0.164445 seconds, bootstrap likelihood -10119.593905, best rearrangement setting 8
Bootstrap[149]: Time 0.146931 seconds, bootstrap likelihood -10248.146733, best rearrangement setting 12
Bootstrap[150]: Time 0.162558 seconds, bootstrap likelihood -10035.731884, best rearrangement setting 14
Bootstrap[151]: Time 0.158847 seconds, bootstrap likelihood -9812.909779, best rearrangement setting 5
Bootstrap[152]: Time 0.156591 seconds, bootstrap likelihood -9917.772957, best rearrangement setting 5
Bootstrap[153]: Time 0.150276 seconds, bootstrap likelihood -10067.701657, best rearrangement setting 13
Bootstrap[154]: Time 0.156220 seconds, bootstrap likelihood -10096.971964, best rearrangement setting 14
Bootstrap[155]: Time 0.147984 seconds, bootstrap likelihood -10174.052778, best rearrangement setting 13
Bootstrap[156]: Time 0.161673 seconds, bootstrap likelihood -9688.431704, best rearrangement setting 11
Bootstrap[157]: Time 0.150199 seconds, bootstrap likelihood -9994.918410, best rearrangement setting 8
Bootstrap[158]: Time 0.161579 seconds, bootstrap likelihood -9965.331882, best rearrangement setting 8
Bootstrap[159]: Time 0.154350 seconds, bootstrap likelihood -9869.513217, best rearrangement setting 5
Bootstrap[160]: Time 0.151920 seconds, bootstrap likelihood -10186.711040, best rearrangement setting 15
Bootstrap[161]: Time 0.146148 seconds, bootstrap likelihood -9884.629917, best rearrangement setting 13
Bootstrap[162]: Time 0.068018 seconds, bootstrap likelihood -9628.159193, best rearrangement setting 13
Bootstrap[163]: Time 0.144659 seconds, bootstrap likelihood -9907.740174, best rearrangement setting 12
Bootstrap[164]: Time 0.131644 seconds, bootstrap likelihood -10125.275341, best rearrangement setting 7
Bootstrap[165]: Time 0.153696 seconds, bootstrap likelihood -9730.541155, best rearrangement setting 13
Bootstrap[166]: Time 0.147514 seconds, bootstrap likelihood -9816.820080, best rearrangement setting 10
Bootstrap[167]: Time 0.146712 seconds, bootstrap likelihood -10185.999599, best rearrangement setting 12
Bootstrap[168]: Time 0.070251 seconds, bootstrap likelihood -10315.366910, best rearrangement setting 14
Bootstrap[169]: Time 0.148319 seconds, bootstrap likelihood -9887.147652, best rearrangement setting 10
Bootstrap[170]: Time 0.070185 seconds, bootstrap likelihood -10025.101372, best rearrangement setting 5
Bootstrap[171]: Time 0.153151 seconds, bootstrap likelihood -9941.539319, best rearrangement setting 11
Bootstrap[172]: Time 0.157749 seconds, bootstrap likelihood -10040.569834, best rearrangement setting 12
Bootstrap[173]: Time 0.159296 seconds, bootstrap likelihood -10184.429036, best rearrangement setting 11
Bootstrap[174]: Time 0.142629 seconds, bootstrap likelihood -9964.259530, best rearrangement setting 15
Bootstrap[175]: Time 0.146325 seconds, bootstrap likelihood -10132.485069, best rearrangement setting 14
Bootstrap[176]: Time 0.139111 seconds, bootstrap likelihood -9899.967996, best rearrangement setting 8
Bootstrap[177]: Time 0.164603 seconds, bootstrap likelihood -10285.781896, best rearrangement setting 8
Bootstrap[178]: Time 0.164613 seconds, bootstrap likelihood -10093.294872, best rearrangement setting 14
Bootstrap[179]: Time 0.139391 seconds, bootstrap likelihood -10172.286321, best rearrangement setting 5
Bootstrap[180]: Time 0.157904 seconds, bootstrap likelihood -9964.042764, best rearrangement setting 12
Bootstrap[181]: Time 0.157608 seconds, bootstrap likelihood -9787.139373, best rearrangement setting 14
Bootstrap[182]: Time 0.147456 seconds, bootstrap likelihood -10182.550428, best rearrangement setting 7
Bootstrap[183]: Time 0.147957 seconds, bootstrap likelihood -10122.851921, best rearrangement setting 11
Bootstrap[184]: Time 0.152924 seconds, bootstrap likelihood -10210.050555, best rearrangement setting 15
Bootstrap[185]: Time 0.156020 seconds, bootstrap likelihood -9815.378541, best rearrangement setting 8
Bootstrap[186]: Time 0.143257 seconds, bootstrap likelihood -9982.094900, best rearrangement setting 13
Bootstrap[187]: Time 0.155733 seconds, bootstrap likelihood -9992.442827, best rearrangement setting 8
Bootstrap[188]: Time 0.142166 seconds, bootstrap likelihood -9873.826933, best rearrangement setting 12
Bootstrap[189]: Time 0.154517 seconds, bootstrap likelihood -9965.308115, best rearrangement setting 11
Bootstrap[190]: Time 0.150121 seconds, bootstrap likelihood -10228.808464, best rearrangement setting 15
Bootstrap[191]: Time 0.075028 seconds, bootstrap likelihood -10000.141716, best rearrangement setting 8
Bootstrap[192]: Time 0.142027 seconds, bootstrap likelihood -9796.250808, best rearrangement setting 8
Bootstrap[193]: Time 0.162307 seconds, bootstrap likelihood -10026.734662, best rearrangement setting 10
Bootstrap[194]: Time 0.157148 seconds, bootstrap likelihood -10155.765841, best rearrangement setting 8
Bootstrap[195]: Time 0.161121 seconds, bootstrap likelihood -10072.605844, best rearrangement setting 7
Bootstrap[196]: Time 0.155392 seconds, bootstrap likelihood -10183.582942, best rearrangement setting 11
Bootstrap[197]: Time 0.160420 seconds, bootstrap likelihood -9990.406786, best rearrangement setting 8
Bootstrap[198]: Time 0.151636 seconds, bootstrap likelihood -9698.174373, best rearrangement setting 15
Bootstrap[199]: Time 0.162119 seconds, bootstrap likelihood -10113.490976, best rearrangement setting 8
Bootstrap[200]: Time 0.156623 seconds, bootstrap likelihood -9831.419355, best rearrangement setting 12
Bootstrap[201]: Time 0.140553 seconds, bootstrap likelihood -9947.374778, best rearrangement setting 10
Bootstrap[202]: Time 0.151746 seconds, bootstrap likelihood -9752.164255, best rearrangement setting 12
Bootstrap[203]: Time 0.153682 seconds, bootstrap likelihood -9851.809805, best rearrangement setting 9
Bootstrap[204]: Time 0.161648 seconds, bootstrap likelihood -9781.304475, best rearrangement setting 7
Bootstrap[205]: Time 0.146097 seconds, bootstrap likelihood -9927.241841, best rearrangement setting 8
Bootstrap[206]: Time 0.153166 seconds, bootstrap likelihood -10284.454302, best rearrangement setting 15
Bootstrap[207]: Time 0.142431 seconds, bootstrap likelihood -10458.305037, best rearrangement setting 10
Bootstrap[208]: Time 0.161203 seconds, bootstrap likelihood -10416.507556, best rearrangement setting 15
Bootstrap[209]: Time 0.140552 seconds, bootstrap likelihood -10161.444511, best rearrangement setting 15
Bootstrap[210]: Time 0.144361 seconds, bootstrap likelihood -10134.715025, best rearrangement setting 8
Bootstrap[211]: Time 0.188638 seconds, bootstrap likelihood -10159.032996, best rearrangement setting 8
Bootstrap[212]: Time 0.150075 seconds, bootstrap likelihood -9961.698546, best rearrangement setting 5
Bootstrap[213]: Time 0.148470 seconds, bootstrap likelihood -9848.213542, best rearrangement setting 6
Bootstrap[214]: Time 0.152758 seconds, bootstrap likelihood -10170.760630, best rearrangement setting 13
Bootstrap[215]: Time 0.158276 seconds, bootstrap likelihood -10244.729488, best rearrangement setting 6
Bootstrap[216]: Time 0.065233 seconds, bootstrap likelihood -9944.863676, best rearrangement setting 13
Bootstrap[217]: Time 0.171928 seconds, bootstrap likelihood -10208.377324, best rearrangement setting 8
Bootstrap[218]: Time 0.148695 seconds, bootstrap likelihood -9992.858210, best rearrangement setting 12
Bootstrap[219]: Time 0.139795 seconds, bootstrap likelihood -10001.486885, best rearrangement setting 6
Bootstrap[220]: Time 0.208691 seconds, bootstrap likelihood -9625.553888, best rearrangement setting 8
Bootstrap[221]: Time 0.182145 seconds, bootstrap likelihood -9900.788626, best rearrangement setting 13
Bootstrap[222]: Time 0.164460 seconds, bootstrap likelihood -10066.296714, best rearrangement setting 6
Bootstrap[223]: Time 0.177264 seconds, bootstrap likelihood -9880.833354, best rearrangement setting 10
Bootstrap[224]: Time 0.161531 seconds, bootstrap likelihood -10137.312401, best rearrangement setting 11
Bootstrap[225]: Time 0.161432 seconds, bootstrap likelihood -10315.240106, best rearrangement setting 13
Bootstrap[226]: Time 0.165169 seconds, bootstrap likelihood -10345.552768, best rearrangement setting 7
Bootstrap[227]: Time 0.145121 seconds, bootstrap likelihood -10272.023464, best rearrangement setting 9
Bootstrap[228]: Time 0.148730 seconds, bootstrap likelihood -9941.274679, best rearrangement setting 13
Bootstrap[229]: Time 0.154899 seconds, bootstrap likelihood -9860.687562, best rearrangement setting 9
Bootstrap[230]: Time 0.150385 seconds, bootstrap likelihood -10305.317311, best rearrangement setting 15
Bootstrap[231]: Time 0.138122 seconds, bootstrap likelihood -9634.745480, best rearrangement setting 12
Bootstrap[232]: Time 0.154578 seconds, bootstrap likelihood -9966.033989, best rearrangement setting 15
Bootstrap[233]: Time 0.155315 seconds, bootstrap likelihood -9793.395335, best rearrangement setting 12
Bootstrap[234]: Time 0.152897 seconds, bootstrap likelihood -10007.549486, best rearrangement setting 6
Bootstrap[235]: Time 0.154889 seconds, bootstrap likelihood -9941.355209, best rearrangement setting 15
Bootstrap[236]: Time 0.157557 seconds, bootstrap likelihood -10154.882151, best rearrangement setting 9
Bootstrap[237]: Time 0.150206 seconds, bootstrap likelihood -9957.527247, best rearrangement setting 5
Bootstrap[238]: Time 0.149653 seconds, bootstrap likelihood -9940.252042, best rearrangement setting 11
Bootstrap[239]: Time 0.147602 seconds, bootstrap likelihood -10060.002258, best rearrangement setting 14
Bootstrap[240]: Time 0.147404 seconds, bootstrap likelihood -10067.298300, best rearrangement setting 13
Bootstrap[241]: Time 0.161151 seconds, bootstrap likelihood -9981.612003, best rearrangement setting 13
Bootstrap[242]: Time 0.072896 seconds, bootstrap likelihood -9955.488958, best rearrangement setting 9
Bootstrap[243]: Time 0.146270 seconds, bootstrap likelihood -9906.685660, best rearrangement setting 14
Bootstrap[244]: Time 0.170349 seconds, bootstrap likelihood -10157.136184, best rearrangement setting 5
Bootstrap[245]: Time 0.145926 seconds, bootstrap likelihood -9851.635702, best rearrangement setting 6
Bootstrap[246]: Time 0.154881 seconds, bootstrap likelihood -9668.350304, best rearrangement setting 5
Bootstrap[247]: Time 0.135666 seconds, bootstrap likelihood -9921.799770, best rearrangement setting 13
Bootstrap[248]: Time 0.155672 seconds, bootstrap likelihood -10090.264648, best rearrangement setting 10
Bootstrap[249]: Time 0.135793 seconds, bootstrap likelihood -9983.153241, best rearrangement setting 7
Bootstrap[250]: Time 0.142071 seconds, bootstrap likelihood -10001.278045, best rearrangement setting 7
Bootstrap[251]: Time 0.153663 seconds, bootstrap likelihood -9884.452510, best rearrangement setting 15
Bootstrap[252]: Time 0.143213 seconds, bootstrap likelihood -10042.488543, best rearrangement setting 6
Bootstrap[253]: Time 0.163273 seconds, bootstrap likelihood -9839.079221, best rearrangement setting 9
Bootstrap[254]: Time 0.151942 seconds, bootstrap likelihood -10269.633557, best rearrangement setting 9
Bootstrap[255]: Time 0.165685 seconds, bootstrap likelihood -10264.449624, best rearrangement setting 8
Bootstrap[256]: Time 0.066506 seconds, bootstrap likelihood -10071.279914, best rearrangement setting 15
Bootstrap[257]: Time 0.153240 seconds, bootstrap likelihood -9615.917503, best rearrangement setting 9
Bootstrap[258]: Time 0.152050 seconds, bootstrap likelihood -9758.158324, best rearrangement setting 11
Bootstrap[259]: Time 0.171888 seconds, bootstrap likelihood -10273.123134, best rearrangement setting 12
Bootstrap[260]: Time 0.072926 seconds, bootstrap likelihood -10248.487814, best rearrangement setting 6
Bootstrap[261]: Time 0.152003 seconds, bootstrap likelihood -9858.200416, best rearrangement setting 5
Bootstrap[262]: Time 0.152293 seconds, bootstrap likelihood -10324.128483, best rearrangement setting 10
Bootstrap[263]: Time 0.066922 seconds, bootstrap likelihood -10027.603430, best rearrangement setting 13
Bootstrap[264]: Time 0.149775 seconds, bootstrap likelihood -10132.825618, best rearrangement setting 11
Bootstrap[265]: Time 0.150963 seconds, bootstrap likelihood -10158.236684, best rearrangement setting 10
Bootstrap[266]: Time 0.154365 seconds, bootstrap likelihood -9912.539814, best rearrangement setting 7
Bootstrap[267]: Time 0.152063 seconds, bootstrap likelihood -9944.725118, best rearrangement setting 11
Bootstrap[268]: Time 0.156247 seconds, bootstrap likelihood -10305.899348, best rearrangement setting 12
Bootstrap[269]: Time 0.156391 seconds, bootstrap likelihood -10131.357523, best rearrangement setting 14
Bootstrap[270]: Time 0.143875 seconds, bootstrap likelihood -9761.297176, best rearrangement setting 6
Bootstrap[271]: Time 0.168606 seconds, bootstrap likelihood -9992.007772, best rearrangement setting 11
Bootstrap[272]: Time 0.148660 seconds, bootstrap likelihood -9677.215248, best rearrangement setting 5
Bootstrap[273]: Time 0.158736 seconds, bootstrap likelihood -10308.076336, best rearrangement setting 10
Bootstrap[274]: Time 0.165220 seconds, bootstrap likelihood -9694.577842, best rearrangement setting 9
Bootstrap[275]: Time 0.157474 seconds, bootstrap likelihood -9974.053315, best rearrangement setting 12
Bootstrap[276]: Time 0.159964 seconds, bootstrap likelihood -10355.632748, best rearrangement setting 10
Bootstrap[277]: Time 0.064654 seconds, bootstrap likelihood -10008.458176, best rearrangement setting 8
Bootstrap[278]: Time 0.072670 seconds, bootstrap likelihood -10071.806978, best rearrangement setting 14
Bootstrap[279]: Time 0.164502 seconds, bootstrap likelihood -10454.473484, best rearrangement setting 5
Bootstrap[280]: Time 0.153857 seconds, bootstrap likelihood -9931.192739, best rearrangement setting 7
Bootstrap[281]: Time 0.152697 seconds, bootstrap likelihood -10136.004892, best rearrangement setting 10
Bootstrap[282]: Time 0.169185 seconds, bootstrap likelihood -9955.528366, best rearrangement setting 12
Bootstrap[283]: Time 0.173875 seconds, bootstrap likelihood -10230.673473, best rearrangement setting 7
Bootstrap[284]: Time 0.160898 seconds, bootstrap likelihood -10168.344585, best rearrangement setting 5
Bootstrap[285]: Time 0.141889 seconds, bootstrap likelihood -9838.365122, best rearrangement setting 6
Bootstrap[286]: Time 0.158395 seconds, bootstrap likelihood -9934.376520, best rearrangement setting 15
Bootstrap[287]: Time 0.181825 seconds, bootstrap likelihood -10363.082237, best rearrangement setting 5
Bootstrap[288]: Time 0.147469 seconds, bootstrap likelihood -10086.525624, best rearrangement setting 13
Bootstrap[289]: Time 0.161776 seconds, bootstrap likelihood -10052.867008, best rearrangement setting 6
Bootstrap[290]: Time 0.174090 seconds, bootstrap likelihood -10023.887006, best rearrangement setting 7
Bootstrap[291]: Time 0.150842 seconds, bootstrap likelihood -9820.281490, best rearrangement setting 11
Bootstrap[292]: Time 0.147333 seconds, bootstrap likelihood -10082.891976, best rearrangement setting 6
Bootstrap[293]: Time 0.144047 seconds, bootstrap likelihood -10015.517770, best rearrangement setting 8
Bootstrap[294]: Time 0.154740 seconds, bootstrap likelihood -9874.068992, best rearrangement setting 12
Bootstrap[295]: Time 0.148826 seconds, bootstrap likelihood -10028.219222, best rearrangement setting 15
Bootstrap[296]: Time 0.069608 seconds, bootstrap likelihood -9521.082760, best rearrangement setting 14
Bootstrap[297]: Time 0.151474 seconds, bootstrap likelihood -9855.144575, best rearrangement setting 10
Bootstrap[298]: Time 0.153687 seconds, bootstrap likelihood -9944.004853, best rearrangement setting 13
Bootstrap[299]: Time 0.159684 seconds, bootstrap likelihood -10057.553032, best rearrangement setting 13
Bootstrap[300]: Time 0.154742 seconds, bootstrap likelihood -10023.811986, best rearrangement setting 11
Bootstrap[301]: Time 0.177799 seconds, bootstrap likelihood -10330.015287, best rearrangement setting 15
Bootstrap[302]: Time 0.166491 seconds, bootstrap likelihood -9734.333671, best rearrangement setting 13
Bootstrap[303]: Time 0.151315 seconds, bootstrap likelihood -10054.107124, best rearrangement setting 11
Bootstrap[304]: Time 0.173549 seconds, bootstrap likelihood -10092.510094, best rearrangement setting 9
Bootstrap[305]: Time 0.165029 seconds, bootstrap likelihood -9727.171926, best rearrangement setting 5
Bootstrap[306]: Time 0.154948 seconds, bootstrap likelihood -9990.172342, best rearrangement setting 12
Bootstrap[307]: Time 0.143890 seconds, bootstrap likelihood -9915.049418, best rearrangement setting 9
Bootstrap[308]: Time 0.151914 seconds, bootstrap likelihood -9884.680791, best rearrangement setting 11
Bootstrap[309]: Time 0.160092 seconds, bootstrap likelihood -9956.949187, best rearrangement setting 9
Bootstrap[310]: Time 0.077665 seconds, bootstrap likelihood -10017.197872, best rearrangement setting 7
Bootstrap[311]: Time 0.145119 seconds, bootstrap likelihood -9771.379766, best rearrangement setting 7
Bootstrap[312]: Time 0.177092 seconds, bootstrap likelihood -10313.151656, best rearrangement setting 8
Bootstrap[313]: Time 0.165132 seconds, bootstrap likelihood -9735.413508, best rearrangement setting 13
Bootstrap[314]: Time 0.158293 seconds, bootstrap likelihood -9773.520306, best rearrangement setting 8
Bootstrap[315]: Time 0.162330 seconds, bootstrap likelihood -9931.696854, best rearrangement setting 5
Bootstrap[316]: Time 0.160603 seconds, bootstrap likelihood -9741.827552, best rearrangement setting 10
Bootstrap[317]: Time 0.163316 seconds, bootstrap likelihood -9913.728765, best rearrangement setting 10
Bootstrap[318]: Time 0.160262 seconds, bootstrap likelihood -10006.860194, best rearrangement setting 14
Bootstrap[319]: Time 0.161357 seconds, bootstrap likelihood -10044.760014, best rearrangement setting 10
Bootstrap[320]: Time 0.145296 seconds, bootstrap likelihood -9922.906063, best rearrangement setting 13
Bootstrap[321]: Time 0.157010 seconds, bootstrap likelihood -9860.984429, best rearrangement setting 13
Bootstrap[322]: Time 0.151177 seconds, bootstrap likelihood -9863.957510, best rearrangement setting 13
Bootstrap[323]: Time 0.160527 seconds, bootstrap likelihood -10061.910475, best rearrangement setting 14
Bootstrap[324]: Time 0.187295 seconds, bootstrap likelihood -10393.509815, best rearrangement setting 12
Bootstrap[325]: Time 0.167144 seconds, bootstrap likelihood -9943.116520, best rearrangement setting 9
Bootstrap[326]: Time 0.156336 seconds, bootstrap likelihood -9867.277176, best rearrangement setting 8
Bootstrap[327]: Time 0.157803 seconds, bootstrap likelihood -9762.393428, best rearrangement setting 7
Bootstrap[328]: Time 0.141472 seconds, bootstrap likelihood -9886.143824, best rearrangement setting 9
Bootstrap[329]: Time 0.155193 seconds, bootstrap likelihood -10081.783571, best rearrangement setting 8
Bootstrap[330]: Time 0.072322 seconds, bootstrap likelihood -9880.714964, best rearrangement setting 8
Bootstrap[331]: Time 0.070844 seconds, bootstrap likelihood -9767.328055, best rearrangement setting 13
Bootstrap[332]: Time 0.151398 seconds, bootstrap likelihood -10200.631130, best rearrangement setting 5
Bootstrap[333]: Time 0.164356 seconds, bootstrap likelihood -10035.486783, best rearrangement setting 9
Bootstrap[334]: Time 0.142289 seconds, bootstrap likelihood -9991.716538, best rearrangement setting 11
Bootstrap[335]: Time 0.150976 seconds, bootstrap likelihood -10168.502686, best rearrangement setting 13
Bootstrap[336]: Time 0.161895 seconds, bootstrap likelihood -10153.665211, best rearrangement setting 14
Bootstrap[337]: Time 0.168874 seconds, bootstrap likelihood -9958.932579, best rearrangement setting 6
Bootstrap[338]: Time 0.167966 seconds, bootstrap likelihood -10169.230945, best rearrangement setting 7
Bootstrap[339]: Time 0.150527 seconds, bootstrap likelihood -9742.632495, best rearrangement setting 6
Bootstrap[340]: Time 0.163848 seconds, bootstrap likelihood -10150.414244, best rearrangement setting 15
Bootstrap[341]: Time 0.151682 seconds, bootstrap likelihood -10082.776938, best rearrangement setting 5
Bootstrap[342]: Time 0.162885 seconds, bootstrap likelihood -9850.830523, best rearrangement setting 13
Bootstrap[343]: Time 0.153622 seconds, bootstrap likelihood -10099.016903, best rearrangement setting 5
Bootstrap[344]: Time 0.162083 seconds, bootstrap likelihood -10121.343056, best rearrangement setting 12
Bootstrap[345]: Time 0.154216 seconds, bootstrap likelihood -10125.097265, best rearrangement setting 11
Bootstrap[346]: Time 0.159438 seconds, bootstrap likelihood -9989.103686, best rearrangement setting 6
Bootstrap[347]: Time 0.147534 seconds, bootstrap likelihood -10159.272475, best rearrangement setting 12
Bootstrap[348]: Time 0.151844 seconds, bootstrap likelihood -9711.122399, best rearrangement setting 5
Bootstrap[349]: Time 0.147615 seconds, bootstrap likelihood -10133.987419, best rearrangement setting 7
Bootstrap[350]: Time 0.158803 seconds, bootstrap likelihood -10085.887696, best rearrangement setting 6
Bootstrap[351]: Time 0.163568 seconds, bootstrap likelihood -9739.976495, best rearrangement setting 6
Bootstrap[352]: Time 0.161671 seconds, bootstrap likelihood -9904.146024, best rearrangement setting 7
Bootstrap[353]: Time 0.068107 seconds, bootstrap likelihood -9611.717238, best rearrangement setting 7
Bootstrap[354]: Time 0.151407 seconds, bootstrap likelihood -9955.046912, best rearrangement setting 11
Bootstrap[355]: Time 0.162880 seconds, bootstrap likelihood -10307.835849, best rearrangement setting 14
Bootstrap[356]: Time 0.158123 seconds, bootstrap likelihood -9690.486592, best rearrangement setting 15
Bootstrap[357]: Time 0.155362 seconds, bootstrap likelihood -9864.078856, best rearrangement setting 11
Bootstrap[358]: Time 0.160957 seconds, bootstrap likelihood -9779.274579, best rearrangement setting 14
Bootstrap[359]: Time 0.163618 seconds, bootstrap likelihood -10128.966303, best rearrangement setting 6
Bootstrap[360]: Time 0.164478 seconds, bootstrap likelihood -10115.951597, best rearrangement setting 6
Bootstrap[361]: Time 0.073404 seconds, bootstrap likelihood -10011.258344, best rearrangement setting 10
Bootstrap[362]: Time 0.155198 seconds, bootstrap likelihood -10016.593127, best rearrangement setting 8
Bootstrap[363]: Time 0.152265 seconds, bootstrap likelihood -10020.571980, best rearrangement setting 10
Bootstrap[364]: Time 0.161588 seconds, bootstrap likelihood -10128.072830, best rearrangement setting 9
Bootstrap[365]: Time 0.158959 seconds, bootstrap likelihood -9785.099231, best rearrangement setting 10
Bootstrap[366]: Time 0.158557 seconds, bootstrap likelihood -9928.987527, best rearrangement setting 8
Bootstrap[367]: Time 0.166361 seconds, bootstrap likelihood -9911.144414, best rearrangement setting 5
Bootstrap[368]: Time 0.176350 seconds, bootstrap likelihood -10194.340060, best rearrangement setting 11
Bootstrap[369]: Time 0.157028 seconds, bootstrap likelihood -10364.081785, best rearrangement setting 13
Bootstrap[370]: Time 0.157736 seconds, bootstrap likelihood -9764.585150, best rearrangement setting 13
Bootstrap[371]: Time 0.153514 seconds, bootstrap likelihood -9738.975211, best rearrangement setting 12
Bootstrap[372]: Time 0.159454 seconds, bootstrap likelihood -10069.721178, best rearrangement setting 10
Bootstrap[373]: Time 0.160290 seconds, bootstrap likelihood -9965.546852, best rearrangement setting 15
Bootstrap[374]: Time 0.152924 seconds, bootstrap likelihood -10111.237738, best rearrangement setting 5
Bootstrap[375]: Time 0.147330 seconds, bootstrap likelihood -9938.830496, best rearrangement setting 15
Bootstrap[376]: Time 0.155926 seconds, bootstrap likelihood -10264.747757, best rearrangement setting 7
Bootstrap[377]: Time 0.148072 seconds, bootstrap likelihood -9964.177837, best rearrangement setting 12
Bootstrap[378]: Time 0.161401 seconds, bootstrap likelihood -9975.673714, best rearrangement setting 13
Bootstrap[379]: Time 0.066567 seconds, bootstrap likelihood -9883.139928, best rearrangement setting 9
Bootstrap[380]: Time 0.166747 seconds, bootstrap likelihood -9668.149835, best rearrangement setting 10
Bootstrap[381]: Time 0.178004 seconds, bootstrap likelihood -9972.728168, best rearrangement setting 6
Bootstrap[382]: Time 0.169276 seconds, bootstrap likelihood -10030.843175, best rearrangement setting 8
Bootstrap[383]: Time 0.166155 seconds, bootstrap likelihood -10297.007388, best rearrangement setting 15
Bootstrap[384]: Time 0.154518 seconds, bootstrap likelihood -9829.855638, best rearrangement setting 10
Bootstrap[385]: Time 0.159037 seconds, bootstrap likelihood -9647.692387, best rearrangement setting 10
Bootstrap[386]: Time 0.163225 seconds, bootstrap likelihood -10127.812134, best rearrangement setting 15
Bootstrap[387]: Time 0.154811 seconds, bootstrap likelihood -9742.455392, best rearrangement setting 12
Bootstrap[388]: Time 0.157281 seconds, bootstrap likelihood -9914.556461, best rearrangement setting 10
Bootstrap[389]: Time 0.168239 seconds, bootstrap likelihood -9796.563786, best rearrangement setting 6
Bootstrap[390]: Time 0.164368 seconds, bootstrap likelihood -9804.772456, best rearrangement setting 14
Bootstrap[391]: Time 0.164753 seconds, bootstrap likelihood -9893.903932, best rearrangement setting 13
Bootstrap[392]: Time 0.160874 seconds, bootstrap likelihood -10115.544728, best rearrangement setting 7
Bootstrap[393]: Time 0.154929 seconds, bootstrap likelihood -10037.557430, best rearrangement setting 13
Bootstrap[394]: Time 0.159513 seconds, bootstrap likelihood -10024.556404, best rearrangement setting 15
Bootstrap[395]: Time 0.155959 seconds, bootstrap likelihood -9969.989425, best rearrangement setting 8
Bootstrap[396]: Time 0.147595 seconds, bootstrap likelihood -9892.797604, best rearrangement setting 7
Bootstrap[397]: Time 0.165882 seconds, bootstrap likelihood -10162.922677, best rearrangement setting 11
Bootstrap[398]: Time 0.139707 seconds, bootstrap likelihood -10004.628414, best rearrangement setting 11
Bootstrap[399]: Time 0.154959 seconds, bootstrap likelihood -10118.209819, best rearrangement setting 8
Bootstrap[400]: Time 0.175178 seconds, bootstrap likelihood -9868.292811, best rearrangement setting 5
Bootstrap[401]: Time 0.072634 seconds, bootstrap likelihood -10035.198239, best rearrangement setting 15
Bootstrap[402]: Time 0.066518 seconds, bootstrap likelihood -10085.952758, best rearrangement setting 5
Bootstrap[403]: Time 0.071081 seconds, bootstrap likelihood -9826.329715, best rearrangement setting 5
Bootstrap[404]: Time 0.068132 seconds, bootstrap likelihood -9819.517894, best rearrangement setting 6
Bootstrap[405]: Time 0.161460 seconds, bootstrap likelihood -9971.495839, best rearrangement setting 15
Bootstrap[406]: Time 0.177637 seconds, bootstrap likelihood -10091.494950, best rearrangement setting 9
Bootstrap[407]: Time 0.173060 seconds, bootstrap likelihood -9798.303940, best rearrangement setting 12
Bootstrap[408]: Time 0.151075 seconds, bootstrap likelihood -10189.906215, best rearrangement setting 9
Bootstrap[409]: Time 0.150560 seconds, bootstrap likelihood -10291.930695, best rearrangement setting 13
Bootstrap[410]: Time 0.163542 seconds, bootstrap likelihood -9931.243867, best rearrangement setting 15
Bootstrap[411]: Time 0.156383 seconds, bootstrap likelihood -10005.799541, best rearrangement setting 14
Bootstrap[412]: Time 0.156179 seconds, bootstrap likelihood -10291.187381, best rearrangement setting 7
Bootstrap[413]: Time 0.141983 seconds, bootstrap likelihood -9499.731271, best rearrangement setting 5
Bootstrap[414]: Time 0.078143 seconds, bootstrap likelihood -10300.768536, best rearrangement setting 6
Bootstrap[415]: Time 0.170329 seconds, bootstrap likelihood -9867.704832, best rearrangement setting 9
Bootstrap[416]: Time 0.169624 seconds, bootstrap likelihood -9922.391377, best rearrangement setting 6
Bootstrap[417]: Time 0.156110 seconds, bootstrap likelihood -9898.410993, best rearrangement setting 10
Bootstrap[418]: Time 0.205169 seconds, bootstrap likelihood -9870.366513, best rearrangement setting 15
Bootstrap[419]: Time 0.179940 seconds, bootstrap likelihood -10017.227674, best rearrangement setting 14
Bootstrap[420]: Time 0.152149 seconds, bootstrap likelihood -10150.084250, best rearrangement setting 5
Bootstrap[421]: Time 0.182051 seconds, bootstrap likelihood -9963.534380, best rearrangement setting 8
Bootstrap[422]: Time 0.151986 seconds, bootstrap likelihood -10016.304558, best rearrangement setting 9
Bootstrap[423]: Time 0.158007 seconds, bootstrap likelihood -10363.822817, best rearrangement setting 14
Bootstrap[424]: Time 0.139306 seconds, bootstrap likelihood -9603.056689, best rearrangement setting 8
Bootstrap[425]: Time 0.154857 seconds, bootstrap likelihood -9614.550935, best rearrangement setting 6
Bootstrap[426]: Time 0.148857 seconds, bootstrap likelihood -9980.189547, best rearrangement setting 7
Bootstrap[427]: Time 0.068336 seconds, bootstrap likelihood -9964.664668, best rearrangement setting 5
Bootstrap[428]: Time 0.066683 seconds, bootstrap likelihood -10366.870508, best rearrangement setting 9
Bootstrap[429]: Time 0.072377 seconds, bootstrap likelihood -10157.182520, best rearrangement setting 15
Bootstrap[430]: Time 0.148379 seconds, bootstrap likelihood -9816.256662, best rearrangement setting 14
Bootstrap[431]: Time 0.144991 seconds, bootstrap likelihood -9940.534411, best rearrangement setting 14
Bootstrap[432]: Time 0.150847 seconds, bootstrap likelihood -9858.882685, best rearrangement setting 8
Bootstrap[433]: Time 0.169468 seconds, bootstrap likelihood -9745.616616, best rearrangement setting 13
Bootstrap[434]: Time 0.074977 seconds, bootstrap likelihood -10014.603401, best rearrangement setting 11
Bootstrap[435]: Time 0.152271 seconds, bootstrap likelihood -10096.922282, best rearrangement setting 8
Bootstrap[436]: Time 0.141702 seconds, bootstrap likelihood -9934.788290, best rearrangement setting 11
Bootstrap[437]: Time 0.132067 seconds, bootstrap likelihood -9850.660525, best rearrangement setting 15
Bootstrap[438]: Time 0.152615 seconds, bootstrap likelihood -9708.964136, best rearrangement setting 15
Bootstrap[439]: Time 0.070161 seconds, bootstrap likelihood -10051.371393, best rearrangement setting 13
Bootstrap[440]: Time 0.146212 seconds, bootstrap likelihood -10113.761168, best rearrangement setting 15
Bootstrap[441]: Time 0.145691 seconds, bootstrap likelihood -9655.805432, best rearrangement setting 14
Bootstrap[442]: Time 0.141333 seconds, bootstrap likelihood -9904.564635, best rearrangement setting 6
Bootstrap[443]: Time 0.151971 seconds, bootstrap likelihood -9998.859384, best rearrangement setting 7
Bootstrap[444]: Time 0.133468 seconds, bootstrap likelihood -9974.140800, best rearrangement setting 13
Bootstrap[445]: Time 0.132758 seconds, bootstrap likelihood -9862.134996, best rearrangement setting 14
Bootstrap[446]: Time 0.147992 seconds, bootstrap likelihood -9917.212817, best rearrangement setting 13
Bootstrap[447]: Time 0.065543 seconds, bootstrap likelihood -9718.640524, best rearrangement setting 11
Bootstrap[448]: Time 0.156766 seconds, bootstrap likelihood -10076.725214, best rearrangement setting 8
Bootstrap[449]: Time 0.151508 seconds, bootstrap likelihood -9941.951352, best rearrangement setting 10
Bootstrap[450]: Time 0.069167 seconds, bootstrap likelihood -10164.474601, best rearrangement setting 9
Bootstrap[451]: Time 0.146476 seconds, bootstrap likelihood -10024.837535, best rearrangement setting 9
Bootstrap[452]: Time 0.146502 seconds, bootstrap likelihood -10191.461312, best rearrangement setting 14
Bootstrap[453]: Time 0.154391 seconds, bootstrap likelihood -9946.264464, best rearrangement setting 10
Bootstrap[454]: Time 0.143181 seconds, bootstrap likelihood -10130.336034, best rearrangement setting 12
Bootstrap[455]: Time 0.150806 seconds, bootstrap likelihood -9862.307692, best rearrangement setting 11
Bootstrap[456]: Time 0.160655 seconds, bootstrap likelihood -9838.010838, best rearrangement setting 7
Bootstrap[457]: Time 0.068363 seconds, bootstrap likelihood -10164.339392, best rearrangement setting 7
Bootstrap[458]: Time 0.153159 seconds, bootstrap likelihood -10164.838201, best rearrangement setting 15
Bootstrap[459]: Time 0.152879 seconds, bootstrap likelihood -10022.008771, best rearrangement setting 8
Bootstrap[460]: Time 0.156627 seconds, bootstrap likelihood -9972.065291, best rearrangement setting 6
Bootstrap[461]: Time 0.165982 seconds, bootstrap likelihood -9986.924314, best rearrangement setting 5
Bootstrap[462]: Time 0.158056 seconds, bootstrap likelihood -10050.561357, best rearrangement setting 8
Bootstrap[463]: Time 0.162519 seconds, bootstrap likelihood -9851.294861, best rearrangement setting 10
Bootstrap[464]: Time 0.154718 seconds, bootstrap likelihood -9890.589879, best rearrangement setting 9
Bootstrap[465]: Time 0.166583 seconds, bootstrap likelihood -9757.242915, best rearrangement setting 8
Bootstrap[466]: Time 0.165405 seconds, bootstrap likelihood -9670.097806, best rearrangement setting 11
Bootstrap[467]: Time 0.131918 seconds, bootstrap likelihood -9715.287608, best rearrangement setting 13
Bootstrap[468]: Time 0.150303 seconds, bootstrap likelihood -10103.319862, best rearrangement setting 10
Bootstrap[469]: Time 0.160212 seconds, bootstrap likelihood -10135.155519, best rearrangement setting 15
Bootstrap[470]: Time 0.154555 seconds, bootstrap likelihood -9929.421609, best rearrangement setting 10
Bootstrap[471]: Time 0.142192 seconds, bootstrap likelihood -9822.816805, best rearrangement setting 7
Bootstrap[472]: Time 0.144380 seconds, bootstrap likelihood -9986.020085, best rearrangement setting 14
Bootstrap[473]: Time 0.158557 seconds, bootstrap likelihood -10091.216507, best rearrangement setting 11
Bootstrap[474]: Time 0.154972 seconds, bootstrap likelihood -10007.664659, best rearrangement setting 10
Bootstrap[475]: Time 0.145021 seconds, bootstrap likelihood -9701.431063, best rearrangement setting 8
Bootstrap[476]: Time 0.150788 seconds, bootstrap likelihood -10009.077388, best rearrangement setting 15
Bootstrap[477]: Time 0.156825 seconds, bootstrap likelihood -10366.066423, best rearrangement setting 9
Bootstrap[478]: Time 0.150355 seconds, bootstrap likelihood -10097.836458, best rearrangement setting 9
Bootstrap[479]: Time 0.155347 seconds, bootstrap likelihood -10151.378264, best rearrangement setting 7
Bootstrap[480]: Time 0.067226 seconds, bootstrap likelihood -9660.139027, best rearrangement setting 9
Bootstrap[481]: Time 0.161151 seconds, bootstrap likelihood -10171.013925, best rearrangement setting 10
Bootstrap[482]: Time 0.157368 seconds, bootstrap likelihood -9984.755602, best rearrangement setting 6
Bootstrap[483]: Time 0.074509 seconds, bootstrap likelihood -10063.526053, best rearrangement setting 6
Bootstrap[484]: Time 0.157367 seconds, bootstrap likelihood -10185.046797, best rearrangement setting 8
Bootstrap[485]: Time 0.136391 seconds, bootstrap likelihood -9762.885348, best rearrangement setting 8
Bootstrap[486]: Time 0.150107 seconds, bootstrap likelihood -10070.235330, best rearrangement setting 10
Bootstrap[487]: Time 0.155541 seconds, bootstrap likelihood -9902.056772, best rearrangement setting 13
Bootstrap[488]: Time 0.158473 seconds, bootstrap likelihood -10131.728780, best rearrangement setting 6
Bootstrap[489]: Time 0.147244 seconds, bootstrap likelihood -10003.326685, best rearrangement setting 5
Bootstrap[490]: Time 0.165661 seconds, bootstrap likelihood -9942.624578, best rearrangement setting 13
Bootstrap[491]: Time 0.160516 seconds, bootstrap likelihood -10088.029140, best rearrangement setting 6
Bootstrap[492]: Time 0.146517 seconds, bootstrap likelihood -10128.715265, best rearrangement setting 14
Bootstrap[493]: Time 0.148687 seconds, bootstrap likelihood -10083.099289, best rearrangement setting 7
Bootstrap[494]: Time 0.147755 seconds, bootstrap likelihood -10172.558680, best rearrangement setting 15
Bootstrap[495]: Time 0.158601 seconds, bootstrap likelihood -9906.439429, best rearrangement setting 13
Bootstrap[496]: Time 0.155952 seconds, bootstrap likelihood -9841.835451, best rearrangement setting 14
Bootstrap[497]: Time 0.159186 seconds, bootstrap likelihood -9885.040359, best rearrangement setting 12
Bootstrap[498]: Time 0.155289 seconds, bootstrap likelihood -9865.970829, best rearrangement setting 6
Bootstrap[499]: Time 0.148274 seconds, bootstrap likelihood -10083.108843, best rearrangement setting 9
Bootstrap[500]: Time 0.152198 seconds, bootstrap likelihood -10201.559884, best rearrangement setting 15
Bootstrap[501]: Time 0.070711 seconds, bootstrap likelihood -10053.037927, best rearrangement setting 13
Bootstrap[502]: Time 0.156417 seconds, bootstrap likelihood -10202.490041, best rearrangement setting 5
Bootstrap[503]: Time 0.158946 seconds, bootstrap likelihood -10295.056948, best rearrangement setting 11
Bootstrap[504]: Time 0.165152 seconds, bootstrap likelihood -9792.314059, best rearrangement setting 10
Bootstrap[505]: Time 0.150249 seconds, bootstrap likelihood -10172.342323, best rearrangement setting 6
Bootstrap[506]: Time 0.151227 seconds, bootstrap likelihood -9835.861689, best rearrangement setting 5
Bootstrap[507]: Time 0.064762 seconds, bootstrap likelihood -9966.253404, best rearrangement setting 9
Bootstrap[508]: Time 0.146988 seconds, bootstrap likelihood -9869.066718, best rearrangement setting 15
Bootstrap[509]: Time 0.159137 seconds, bootstrap likelihood -9893.782450, best rearrangement setting 14
Bootstrap[510]: Time 0.159896 seconds, bootstrap likelihood -10089.092078, best rearrangement setting 5
Bootstrap[511]: Time 0.142197 seconds, bootstrap likelihood -9760.309924, best rearrangement setting 11
Bootstrap[512]: Time 0.069472 seconds, bootstrap likelihood -9982.983384, best rearrangement setting 14
Bootstrap[513]: Time 0.067182 seconds, bootstrap likelihood -9681.258377, best rearrangement setting 12
Bootstrap[514]: Time 0.064530 seconds, bootstrap likelihood -10038.330225, best rearrangement setting 9
Bootstrap[515]: Time 0.063764 seconds, bootstrap likelihood -9806.348144, best rearrangement setting 6
Bootstrap[516]: Time 0.072955 seconds, bootstrap likelihood -9664.912519, best rearrangement setting 6
Bootstrap[517]: Time 0.143399 seconds, bootstrap likelihood -9719.696668, best rearrangement setting 6
Bootstrap[518]: Time 0.073135 seconds, bootstrap likelihood -10011.424124, best rearrangement setting 9
Bootstrap[519]: Time 0.141140 seconds, bootstrap likelihood -9539.225678, best rearrangement setting 13
Bootstrap[520]: Time 0.154576 seconds, bootstrap likelihood -10006.125146, best rearrangement setting 9
Bootstrap[521]: Time 0.076650 seconds, bootstrap likelihood -9547.213322, best rearrangement setting 10
Bootstrap[522]: Time 0.142229 seconds, bootstrap likelihood -9692.612757, best rearrangement setting 7
Bootstrap[523]: Time 0.145367 seconds, bootstrap likelihood -10119.687118, best rearrangement setting 6
Bootstrap[524]: Time 0.155414 seconds, bootstrap likelihood -9899.496118, best rearrangement setting 11
Bootstrap[525]: Time 0.068383 seconds, bootstrap likelihood -9978.825518, best rearrangement setting 8
Bootstrap[526]: Time 0.152555 seconds, bootstrap likelihood -9875.297426, best rearrangement setting 14
Bootstrap[527]: Time 0.152973 seconds, bootstrap likelihood -10160.171955, best rearrangement setting 12
Bootstrap[528]: Time 0.160205 seconds, bootstrap likelihood -10127.166933, best rearrangement setting 11
Bootstrap[529]: Time 0.156669 seconds, bootstrap likelihood -9695.677075, best rearrangement setting 7
Bootstrap[530]: Time 0.160291 seconds, bootstrap likelihood -10138.772022, best rearrangement setting 7
Bootstrap[531]: Time 0.150624 seconds, bootstrap likelihood -10033.295410, best rearrangement setting 12
Bootstrap[532]: Time 0.150540 seconds, bootstrap likelihood -10141.005819, best rearrangement setting 10
Bootstrap[533]: Time 0.158119 seconds, bootstrap likelihood -10114.721195, best rearrangement setting 12
Bootstrap[534]: Time 0.147536 seconds, bootstrap likelihood -9797.323464, best rearrangement setting 15
Bootstrap[535]: Time 0.153098 seconds, bootstrap likelihood -10051.792893, best rearrangement setting 6
Bootstrap[536]: Time 0.141521 seconds, bootstrap likelihood -10146.944292, best rearrangement setting 8
Bootstrap[537]: Time 0.150383 seconds, bootstrap likelihood -9870.701661, best rearrangement setting 8
Bootstrap[538]: Time 0.068297 seconds, bootstrap likelihood -10003.417855, best rearrangement setting 12
Bootstrap[539]: Time 0.075327 seconds, bootstrap likelihood -10138.589092, best rearrangement setting 9
Bootstrap[540]: Time 0.157481 seconds, bootstrap likelihood -9962.035146, best rearrangement setting 7
Bootstrap[541]: Time 0.138465 seconds, bootstrap likelihood -9638.271710, best rearrangement setting 7
Bootstrap[542]: Time 0.143346 seconds, bootstrap likelihood -9829.325035, best rearrangement setting 9
Bootstrap[543]: Time 0.161091 seconds, bootstrap likelihood -10074.446175, best rearrangement setting 8
Bootstrap[544]: Time 0.150271 seconds, bootstrap likelihood -9982.222930, best rearrangement setting 14
Bootstrap[545]: Time 0.175216 seconds, bootstrap likelihood -9910.342559, best rearrangement setting 10
Bootstrap[546]: Time 0.070963 seconds, bootstrap likelihood -10429.306679, best rearrangement setting 13
Bootstrap[547]: Time 0.159735 seconds, bootstrap likelihood -9899.809186, best rearrangement setting 8
Bootstrap[548]: Time 0.165847 seconds, bootstrap likelihood -10033.989437, best rearrangement setting 9
Bootstrap[549]: Time 0.148781 seconds, bootstrap likelihood -10033.796484, best rearrangement setting 12
Bootstrap[550]: Time 0.152014 seconds, bootstrap likelihood -10085.332357, best rearrangement setting 5
Bootstrap[551]: Time 0.069196 seconds, bootstrap likelihood -10144.011778, best rearrangement setting 10
Bootstrap[552]: Time 0.159478 seconds, bootstrap likelihood -10351.343027, best rearrangement setting 15
Bootstrap[553]: Time 0.072377 seconds, bootstrap likelihood -10410.835210, best rearrangement setting 13
Bootstrap[554]: Time 0.164934 seconds, bootstrap likelihood -10098.228923, best rearrangement setting 9
Bootstrap[555]: Time 0.165761 seconds, bootstrap likelihood -10210.740076, best rearrangement setting 9
Bootstrap[556]: Time 0.072504 seconds, bootstrap likelihood -9947.920143, best rearrangement setting 8
Bootstrap[557]: Time 0.141108 seconds, bootstrap likelihood -9666.317459, best rearrangement setting 12
Bootstrap[558]: Time 0.158994 seconds, bootstrap likelihood -10146.274210, best rearrangement setting 10
Bootstrap[559]: Time 0.113903 seconds, bootstrap likelihood -9922.858180, best rearrangement setting 13
Bootstrap[560]: Time 0.181670 seconds, bootstrap likelihood -10107.987104, best rearrangement setting 10
Bootstrap[561]: Time 0.169409 seconds, bootstrap likelihood -10015.196358, best rearrangement setting 7
Bootstrap[562]: Time 0.177285 seconds, bootstrap likelihood -10078.534820, best rearrangement setting 10
Bootstrap[563]: Time 0.157613 seconds, bootstrap likelihood -9913.246163, best rearrangement setting 12
Bootstrap[564]: Time 0.159328 seconds, bootstrap likelihood -10226.749695, best rearrangement setting 13
Bootstrap[565]: Time 0.149010 seconds, bootstrap likelihood -10047.755946, best rearrangement setting 12
Bootstrap[566]: Time 0.151588 seconds, bootstrap likelihood -10352.215226, best rearrangement setting 12
Bootstrap[567]: Time 0.164590 seconds, bootstrap likelihood -9729.606006, best rearrangement setting 9
Bootstrap[568]: Time 0.063527 seconds, bootstrap likelihood -9888.916836, best rearrangement setting 10
Bootstrap[569]: Time 0.065695 seconds, bootstrap likelihood -9762.018623, best rearrangement setting 7
Bootstrap[570]: Time 0.155513 seconds, bootstrap likelihood -9794.123703, best rearrangement setting 5
Bootstrap[571]: Time 0.157339 seconds, bootstrap likelihood -9932.501410, best rearrangement setting 13
Bootstrap[572]: Time 0.157882 seconds, bootstrap likelihood -9844.768237, best rearrangement setting 12
Bootstrap[573]: Time 0.151642 seconds, bootstrap likelihood -9607.433664, best rearrangement setting 12
Bootstrap[574]: Time 0.146979 seconds, bootstrap likelihood -9961.134755, best rearrangement setting 5
Bootstrap[575]: Time 0.066007 seconds, bootstrap likelihood -10371.823925, best rearrangement setting 14
Bootstrap[576]: Time 0.151445 seconds, bootstrap likelihood -9712.323761, best rearrangement setting 11
Bootstrap[577]: Time 0.162378 seconds, bootstrap likelihood -10075.011156, best rearrangement setting 6
Bootstrap[578]: Time 0.149191 seconds, bootstrap likelihood -10434.580818, best rearrangement setting 7
Bootstrap[579]: Time 0.142063 seconds, bootstrap likelihood -10282.566330, best rearrangement setting 15
Bootstrap[580]: Time 0.075829 seconds, bootstrap likelihood -10007.112454, best rearrangement setting 10
Bootstrap[581]: Time 0.143805 seconds, bootstrap likelihood -10054.292422, best rearrangement setting 10
Bootstrap[582]: Time 0.154284 seconds, bootstrap likelihood -9904.307201, best rearrangement setting 11
Bootstrap[583]: Time 0.157933 seconds, bootstrap likelihood -10173.752601, best rearrangement setting 11
Bootstrap[584]: Time 0.148396 seconds, bootstrap likelihood -9822.847831, best rearrangement setting 14
Bootstrap[585]: Time 0.145410 seconds, bootstrap likelihood -9932.655901, best rearrangement setting 14
Bootstrap[586]: Time 0.153278 seconds, bootstrap likelihood -10033.999832, best rearrangement setting 10
Bootstrap[587]: Time 0.133070 seconds, bootstrap likelihood -9812.852563, best rearrangement setting 14
Bootstrap[588]: Time 0.154745 seconds, bootstrap likelihood -9958.485462, best rearrangement setting 11
Bootstrap[589]: Time 0.170423 seconds, bootstrap likelihood -9986.285304, best rearrangement setting 5
Bootstrap[590]: Time 0.142038 seconds, bootstrap likelihood -9846.878996, best rearrangement setting 9
Bootstrap[591]: Time 0.154863 seconds, bootstrap likelihood -9990.500096, best rearrangement setting 6
Bootstrap[592]: Time 0.150349 seconds, bootstrap likelihood -10102.715054, best rearrangement setting 7
Bootstrap[593]: Time 0.148109 seconds, bootstrap likelihood -9990.274035, best rearrangement setting 5
Bootstrap[594]: Time 0.158756 seconds, bootstrap likelihood -9929.128586, best rearrangement setting 10
Bootstrap[595]: Time 0.159023 seconds, bootstrap likelihood -9852.503260, best rearrangement setting 5
Bootstrap[596]: Time 0.141618 seconds, bootstrap likelihood -9844.125474, best rearrangement setting 12
Bootstrap[597]: Time 0.152585 seconds, bootstrap likelihood -10112.753581, best rearrangement setting 15
Bootstrap[598]: Time 0.150495 seconds, bootstrap likelihood -10255.640198, best rearrangement setting 10
Bootstrap[599]: Time 0.160482 seconds, bootstrap likelihood -10075.553477, best rearrangement setting 13
Bootstrap[600]: Time 0.072760 seconds, bootstrap likelihood -10330.539616, best rearrangement setting 6
Bootstrap[601]: Time 0.161510 seconds, bootstrap likelihood -10096.312923, best rearrangement setting 6
Bootstrap[602]: Time 0.146502 seconds, bootstrap likelihood -9967.771536, best rearrangement setting 12
Bootstrap[603]: Time 0.157014 seconds, bootstrap likelihood -9952.512722, best rearrangement setting 12
Bootstrap[604]: Time 0.136925 seconds, bootstrap likelihood -9783.024411, best rearrangement setting 7
Bootstrap[605]: Time 0.173998 seconds, bootstrap likelihood -9866.443010, best rearrangement setting 9
Bootstrap[606]: Time 0.154904 seconds, bootstrap likelihood -9827.342525, best rearrangement setting 9
Bootstrap[607]: Time 0.158441 seconds, bootstrap likelihood -10135.284413, best rearrangement setting 5
Bootstrap[608]: Time 0.161283 seconds, bootstrap likelihood -9975.686635, best rearrangement setting 11
Bootstrap[609]: Time 0.146398 seconds, bootstrap likelihood -9930.086502, best rearrangement setting 5
Bootstrap[610]: Time 0.158731 seconds, bootstrap likelihood -9932.373253, best rearrangement setting 12
Bootstrap[611]: Time 0.165901 seconds, bootstrap likelihood -10203.650549, best rearrangement setting 15
Bootstrap[612]: Time 0.154657 seconds, bootstrap likelihood -10032.323582, best rearrangement setting 5
Bootstrap[613]: Time 0.155179 seconds, bootstrap likelihood -9906.193599, best rearrangement setting 9
Bootstrap[614]: Time 0.155957 seconds, bootstrap likelihood -9823.069633, best rearrangement setting 7
Bootstrap[615]: Time 0.156938 seconds, bootstrap likelihood -9714.403591, best rearrangement setting 14
Bootstrap[616]: Time 0.162532 seconds, bootstrap likelihood -9926.442878, best rearrangement setting 11
Bootstrap[617]: Time 0.068916 seconds, bootstrap likelihood -10425.304755, best rearrangement setting 15
Bootstrap[618]: Time 0.066101 seconds, bootstrap likelihood -9650.843640, best rearrangement setting 8
Bootstrap[619]: Time 0.169190 seconds, bootstrap likelihood -9950.403635, best rearrangement setting 11
Bootstrap[620]: Time 0.155994 seconds, bootstrap likelihood -9794.482570, best rearrangement setting 5
Bootstrap[621]: Time 0.158848 seconds, bootstrap likelihood -9947.901286, best rearrangement setting 7
Bootstrap[622]: Time 0.133873 seconds, bootstrap likelihood -10001.574278, best rearrangement setting 15
Bootstrap[623]: Time 0.156202 seconds, bootstrap likelihood -10230.751887, best rearrangement setting 9
Bootstrap[624]: Time 0.161885 seconds, bootstrap likelihood -10152.920842, best rearrangement setting 9
Bootstrap[625]: Time 0.073266 seconds, bootstrap likelihood -10141.341439, best rearrangement setting 5
Bootstrap[626]: Time 0.165123 seconds, bootstrap likelihood -10300.117654, best rearrangement setting 10
Bootstrap[627]: Time 0.167290 seconds, bootstrap likelihood -10288.233332, best rearrangement setting 15
Bootstrap[628]: Time 0.165462 seconds, bootstrap likelihood -10119.431006, best rearrangement setting 13
Bootstrap[629]: Time 0.155488 seconds, bootstrap likelihood -9966.970575, best rearrangement setting 13
Bootstrap[630]: Time 0.146579 seconds, bootstrap likelihood -10044.255629, best rearrangement setting 7
Bootstrap[631]: Time 0.165358 seconds, bootstrap likelihood -10292.344902, best rearrangement setting 5
Bootstrap[632]: Time 0.150022 seconds, bootstrap likelihood -10067.305823, best rearrangement setting 15
Bootstrap[633]: Time 0.159085 seconds, bootstrap likelihood -9566.773124, best rearrangement setting 5
Bootstrap[634]: Time 0.071346 seconds, bootstrap likelihood -10008.632581, best rearrangement setting 14
Bootstrap[635]: Time 0.065359 seconds, bootstrap likelihood -9780.960592, best rearrangement setting 10
Bootstrap[636]: Time 0.156102 seconds, bootstrap likelihood -9812.209234, best rearrangement setting 10
Bootstrap[637]: Time 0.143116 seconds, bootstrap likelihood -9843.553849, best rearrangement setting 11
Bootstrap[638]: Time 0.159631 seconds, bootstrap likelihood -10049.178124, best rearrangement setting 13
Bootstrap[639]: Time 0.142710 seconds, bootstrap likelihood -9808.201349, best rearrangement setting 9
Bootstrap[640]: Time 0.173500 seconds, bootstrap likelihood -9807.767979, best rearrangement setting 14
Bootstrap[641]: Time 0.151125 seconds, bootstrap likelihood -10267.905970, best rearrangement setting 12
Bootstrap[642]: Time 0.164919 seconds, bootstrap likelihood -10377.224241, best rearrangement setting 15
Bootstrap[643]: Time 0.161211 seconds, bootstrap likelihood -9991.145496, best rearrangement setting 14
Bootstrap[644]: Time 0.153990 seconds, bootstrap likelihood -9897.583942, best rearrangement setting 7
Bootstrap[645]: Time 0.156286 seconds, bootstrap likelihood -10205.928868, best rearrangement setting 6
Bootstrap[646]: Time 0.158908 seconds, bootstrap likelihood -9938.821380, best rearrangement setting 13
Bootstrap[647]: Time 0.153254 seconds, bootstrap likelihood -9961.433598, best rearrangement setting 6
Bootstrap[648]: Time 0.155049 seconds, bootstrap likelihood -10046.604652, best rearrangement setting 13
Bootstrap[649]: Time 0.144834 seconds, bootstrap likelihood -9919.937780, best rearrangement setting 7
Bootstrap[650]: Time 0.167334 seconds, bootstrap likelihood -10211.652441, best rearrangement setting 12
Bootstrap[651]: Time 0.163220 seconds, bootstrap likelihood -10103.113983, best rearrangement setting 12
Bootstrap[652]: Time 0.157194 seconds, bootstrap likelihood -9767.588565, best rearrangement setting 15
Bootstrap[653]: Time 0.149119 seconds, bootstrap likelihood -9972.470673, best rearrangement setting 15
Bootstrap[654]: Time 0.139079 seconds, bootstrap likelihood -10027.993254, best rearrangement setting 6
Bootstrap[655]: Time 0.070939 seconds, bootstrap likelihood -10208.571491, best rearrangement setting 5
Bootstrap[656]: Time 0.141774 seconds, bootstrap likelihood -10040.632647, best rearrangement setting 6
Bootstrap[657]: Time 0.150196 seconds, bootstrap likelihood -9928.882632, best rearrangement setting 14
Bootstrap[658]: Time 0.154789 seconds, bootstrap likelihood -9940.522021, best rearrangement setting 13
Bootstrap[659]: Time 0.072728 seconds, bootstrap likelihood -10201.603442, best rearrangement setting 7
Bootstrap[660]: Time 0.156789 seconds, bootstrap likelihood -10036.660116, best rearrangement setting 12
Bootstrap[661]: Time 0.149531 seconds, bootstrap likelihood -9945.138679, best rearrangement setting 10
Bootstrap[662]: Time 0.159952 seconds, bootstrap likelihood -10153.662828, best rearrangement setting 14
Bootstrap[663]: Time 0.149195 seconds, bootstrap likelihood -9922.865715, best rearrangement setting 12
Bootstrap[664]: Time 0.170364 seconds, bootstrap likelihood -10037.886051, best rearrangement setting 12
Bootstrap[665]: Time 0.153568 seconds, bootstrap likelihood -9809.847924, best rearrangement setting 9
Bootstrap[666]: Time 0.154059 seconds, bootstrap likelihood -10002.051983, best rearrangement setting 12
Bootstrap[667]: Time 0.146126 seconds, bootstrap likelihood -9840.375943, best rearrangement setting 11
Bootstrap[668]: Time 0.186395 seconds, bootstrap likelihood -9892.454070, best rearrangement setting 7
Bootstrap[669]: Time 0.150700 seconds, bootstrap likelihood -9946.633073, best rearrangement setting 12
Bootstrap[670]: Time 0.158456 seconds, bootstrap likelihood -10187.351147, best rearrangement setting 5
Bootstrap[671]: Time 0.155251 seconds, bootstrap likelihood -9959.159801, best rearrangement setting 5
Bootstrap[672]: Time 0.149237 seconds, bootstrap likelihood -10066.096668, best rearrangement setting 10
Bootstrap[673]: Time 0.154011 seconds, bootstrap likelihood -9619.215330, best rearrangement setting 11
Bootstrap[674]: Time 0.145582 seconds, bootstrap likelihood -10084.898156, best rearrangement setting 11
Bootstrap[675]: Time 0.149202 seconds, bootstrap likelihood -10144.835185, best rearrangement setting 12
Bootstrap[676]: Time 0.170510 seconds, bootstrap likelihood -10185.454590, best rearrangement setting 6
Bootstrap[677]: Time 0.152451 seconds, bootstrap likelihood -10025.772724, best rearrangement setting 11
Bootstrap[678]: Time 0.149792 seconds, bootstrap likelihood -9826.182851, best rearrangement setting 15
Bootstrap[679]: Time 0.149776 seconds, bootstrap likelihood -10197.449335, best rearrangement setting 9
Bootstrap[680]: Time 0.163865 seconds, bootstrap likelihood -9715.828173, best rearrangement setting 10
Bootstrap[681]: Time 0.159125 seconds, bootstrap likelihood -10135.913649, best rearrangement setting 5
Bootstrap[682]: Time 0.150680 seconds, bootstrap likelihood -9910.484421, best rearrangement setting 5
Bootstrap[683]: Time 0.064531 seconds, bootstrap likelihood -10329.965196, best rearrangement setting 10
Bootstrap[684]: Time 0.146143 seconds, bootstrap likelihood -9904.502589, best rearrangement setting 10
Bootstrap[685]: Time 0.154267 seconds, bootstrap likelihood -9925.855624, best rearrangement setting 6
Bootstrap[686]: Time 0.073747 seconds, bootstrap likelihood -9567.157272, best rearrangement setting 5
Bootstrap[687]: Time 0.159952 seconds, bootstrap likelihood -9921.791861, best rearrangement setting 12
Bootstrap[688]: Time 0.152030 seconds, bootstrap likelihood -10057.915464, best rearrangement setting 13
Bootstrap[689]: Time 0.075935 seconds, bootstrap likelihood -9972.705395, best rearrangement setting 14
Bootstrap[690]: Time 0.141561 seconds, bootstrap likelihood -9991.246032, best rearrangement setting 7
Bootstrap[691]: Time 0.154146 seconds, bootstrap likelihood -10046.767394, best rearrangement setting 6
Bootstrap[692]: Time 0.068687 seconds, bootstrap likelihood -10372.993298, best rearrangement setting 7
Bootstrap[693]: Time 0.159801 seconds, bootstrap likelihood -9958.417117, best rearrangement setting 9
Bootstrap[694]: Time 0.144897 seconds, bootstrap likelihood -9872.866790, best rearrangement setting 15
Bootstrap[695]: Time 0.134553 seconds, bootstrap likelihood -10227.066252, best rearrangement setting 10
Bootstrap[696]: Time 0.065081 seconds, bootstrap likelihood -10082.425903, best rearrangement setting 11
Bootstrap[697]: Time 0.155170 seconds, bootstrap likelihood -10103.598150, best rearrangement setting 9
Bootstrap[698]: Time 0.152878 seconds, bootstrap likelihood -9937.565455, best rearrangement setting 5
Bootstrap[699]: Time 0.168229 seconds, bootstrap likelihood -9945.942457, best rearrangement setting 10
Bootstrap[700]: Time 0.162951 seconds, bootstrap likelihood -9944.119241, best rearrangement setting 8
Bootstrap[701]: Time 0.139823 seconds, bootstrap likelihood -9869.346656, best rearrangement setting 5
Bootstrap[702]: Time 0.160203 seconds, bootstrap likelihood -9756.609176, best rearrangement setting 6
Bootstrap[703]: Time 0.140796 seconds, bootstrap likelihood -9990.221589, best rearrangement setting 10
Bootstrap[704]: Time 0.148171 seconds, bootstrap likelihood -10009.852666, best rearrangement setting 6
Bootstrap[705]: Time 0.140573 seconds, bootstrap likelihood -9974.665880, best rearrangement setting 8
Bootstrap[706]: Time 0.066174 seconds, bootstrap likelihood -9918.101703, best rearrangement setting 15
Bootstrap[707]: Time 0.153936 seconds, bootstrap likelihood -10074.248030, best rearrangement setting 5
Bootstrap[708]: Time 0.144162 seconds, bootstrap likelihood -10214.252985, best rearrangement setting 11
Bootstrap[709]: Time 0.071783 seconds, bootstrap likelihood -9929.294052, best rearrangement setting 10
Bootstrap[710]: Time 0.153536 seconds, bootstrap likelihood -9773.512070, best rearrangement setting 9
Bootstrap[711]: Time 0.153385 seconds, bootstrap likelihood -9812.909143, best rearrangement setting 11
Bootstrap[712]: Time 0.072856 seconds, bootstrap likelihood -10263.408185, best rearrangement setting 5
Bootstrap[713]: Time 0.075632 seconds, bootstrap likelihood -10288.014809, best rearrangement setting 13
Bootstrap[714]: Time 0.159824 seconds, bootstrap likelihood -10074.076354, best rearrangement setting 12
Bootstrap[715]: Time 0.152430 seconds, bootstrap likelihood -10116.670975, best rearrangement setting 5
Bootstrap[716]: Time 0.151873 seconds, bootstrap likelihood -9894.960983, best rearrangement setting 11
Bootstrap[717]: Time 0.145807 seconds, bootstrap likelihood -9829.451766, best rearrangement setting 12
Bootstrap[718]: Time 0.155469 seconds, bootstrap likelihood -9829.912219, best rearrangement setting 8
Bootstrap[719]: Time 0.155767 seconds, bootstrap likelihood -9863.521816, best rearrangement setting 13
Bootstrap[720]: Time 0.146997 seconds, bootstrap likelihood -9944.503013, best rearrangement setting 5
Bootstrap[721]: Time 0.144509 seconds, bootstrap likelihood -9851.394681, best rearrangement setting 13
Bootstrap[722]: Time 0.142304 seconds, bootstrap likelihood -9710.730765, best rearrangement setting 12
Bootstrap[723]: Time 0.143743 seconds, bootstrap likelihood -9974.852050, best rearrangement setting 11
Bootstrap[724]: Time 0.150284 seconds, bootstrap likelihood -10016.908855, best rearrangement setting 14
Bootstrap[725]: Time 0.149148 seconds, bootstrap likelihood -9713.244232, best rearrangement setting 5
Bootstrap[726]: Time 0.160806 seconds, bootstrap likelihood -9903.437694, best rearrangement setting 15
Bootstrap[727]: Time 0.152620 seconds, bootstrap likelihood -10089.054999, best rearrangement setting 6
Bootstrap[728]: Time 0.165143 seconds, bootstrap likelihood -10062.945009, best rearrangement setting 6
Bootstrap[729]: Time 0.151673 seconds, bootstrap likelihood -10227.766834, best rearrangement setting 10
Bootstrap[730]: Time 0.163518 seconds, bootstrap likelihood -10127.862904, best rearrangement setting 12
Bootstrap[731]: Time 0.165966 seconds, bootstrap likelihood -9960.639212, best rearrangement setting 11
Bootstrap[732]: Time 0.150047 seconds, bootstrap likelihood -9885.752690, best rearrangement setting 6
Bootstrap[733]: Time 0.074064 seconds, bootstrap likelihood -10259.269253, best rearrangement setting 6
Bootstrap[734]: Time 0.147127 seconds, bootstrap likelihood -10130.189224, best rearrangement setting 11
Bootstrap[735]: Time 0.129786 seconds, bootstrap likelihood -10078.330681, best rearrangement setting 14
Bootstrap[736]: Time 0.146437 seconds, bootstrap likelihood -9840.027397, best rearrangement setting 11
Bootstrap[737]: Time 0.174954 seconds, bootstrap likelihood -9674.774416, best rearrangement setting 10
Bootstrap[738]: Time 0.162975 seconds, bootstrap likelihood -10233.593256, best rearrangement setting 7
Bootstrap[739]: Time 0.157078 seconds, bootstrap likelihood -10129.208935, best rearrangement setting 5
Bootstrap[740]: Time 0.162232 seconds, bootstrap likelihood -9983.413202, best rearrangement setting 9
Bootstrap[741]: Time 0.074921 seconds, bootstrap likelihood -10162.811582, best rearrangement setting 5
Bootstrap[742]: Time 0.076123 seconds, bootstrap likelihood -10135.129076, best rearrangement setting 9
Bootstrap[743]: Time 0.155400 seconds, bootstrap likelihood -9840.890730, best rearrangement setting 13
Bootstrap[744]: Time 0.143077 seconds, bootstrap likelihood -9975.503746, best rearrangement setting 7
Bootstrap[745]: Time 0.159650 seconds, bootstrap likelihood -9932.733895, best rearrangement setting 12
Bootstrap[746]: Time 0.156748 seconds, bootstrap likelihood -9973.700274, best rearrangement setting 14
Bootstrap[747]: Time 0.176706 seconds, bootstrap likelihood -9896.841754, best rearrangement setting 13
Bootstrap[748]: Time 0.152827 seconds, bootstrap likelihood -10199.926984, best rearrangement setting 5
Bootstrap[749]: Time 0.150487 seconds, bootstrap likelihood -10012.877835, best rearrangement setting 10
Bootstrap[750]: Time 0.171708 seconds, bootstrap likelihood -9911.622712, best rearrangement setting 10
Bootstrap[751]: Time 0.154461 seconds, bootstrap likelihood -9836.407089, best rearrangement setting 7
Bootstrap[752]: Time 0.160656 seconds, bootstrap likelihood -9892.405513, best rearrangement setting 13
Bootstrap[753]: Time 0.156760 seconds, bootstrap likelihood -10054.495754, best rearrangement setting 8
Bootstrap[754]: Time 0.148092 seconds, bootstrap likelihood -9963.842100, best rearrangement setting 12
Bootstrap[755]: Time 0.153501 seconds, bootstrap likelihood -9639.162404, best rearrangement setting 5
Bootstrap[756]: Time 0.168180 seconds, bootstrap likelihood -10118.987490, best rearrangement setting 5
Bootstrap[757]: Time 0.152846 seconds, bootstrap likelihood -9951.468714, best rearrangement setting 14
Bootstrap[758]: Time 0.150798 seconds, bootstrap likelihood -10009.744467, best rearrangement setting 6
Bootstrap[759]: Time 0.162322 seconds, bootstrap likelihood -9972.165344, best rearrangement setting 11
Bootstrap[760]: Time 0.156673 seconds, bootstrap likelihood -10482.585885, best rearrangement setting 7
Bootstrap[761]: Time 0.157080 seconds, bootstrap likelihood -10077.523039, best rearrangement setting 6
Bootstrap[762]: Time 0.071644 seconds, bootstrap likelihood -9923.061977, best rearrangement setting 6
Bootstrap[763]: Time 0.180788 seconds, bootstrap likelihood -9803.875990, best rearrangement setting 12
Bootstrap[764]: Time 0.172498 seconds, bootstrap likelihood -9975.725288, best rearrangement setting 10
Bootstrap[765]: Time 0.144287 seconds, bootstrap likelihood -10233.120139, best rearrangement setting 9
Bootstrap[766]: Time 0.156646 seconds, bootstrap likelihood -10132.448438, best rearrangement setting 15
Bootstrap[767]: Time 0.134604 seconds, bootstrap likelihood -9819.072823, best rearrangement setting 14
Bootstrap[768]: Time 0.067782 seconds, bootstrap likelihood -9835.948199, best rearrangement setting 15
Bootstrap[769]: Time 0.072510 seconds, bootstrap likelihood -9998.473353, best rearrangement setting 15
Bootstrap[770]: Time 0.147045 seconds, bootstrap likelihood -9955.304632, best rearrangement setting 9
Bootstrap[771]: Time 0.176872 seconds, bootstrap likelihood -10187.945261, best rearrangement setting 10
Bootstrap[772]: Time 0.146457 seconds, bootstrap likelihood -9989.937096, best rearrangement setting 14
Bootstrap[773]: Time 0.143799 seconds, bootstrap likelihood -9907.708358, best rearrangement setting 6
Bootstrap[774]: Time 0.153651 seconds, bootstrap likelihood -10178.058517, best rearrangement setting 6
Bootstrap[775]: Time 0.154358 seconds, bootstrap likelihood -10091.498042, best rearrangement setting 5
Bootstrap[776]: Time 0.071758 seconds, bootstrap likelihood -10029.619704, best rearrangement setting 14
Bootstrap[777]: Time 0.155910 seconds, bootstrap likelihood -10201.986178, best rearrangement setting 9
Bootstrap[778]: Time 0.150117 seconds, bootstrap likelihood -10000.715456, best rearrangement setting 9
Bootstrap[779]: Time 0.164198 seconds, bootstrap likelihood -10052.052683, best rearrangement setting 15
Bootstrap[780]: Time 0.164976 seconds, bootstrap likelihood -10131.829981, best rearrangement setting 8
Bootstrap[781]: Time 0.134148 seconds, bootstrap likelihood -9813.834557, best rearrangement setting 13
Bootstrap[782]: Time 0.151364 seconds, bootstrap likelihood -10081.844043, best rearrangement setting 5
Bootstrap[783]: Time 0.132475 seconds, bootstrap likelihood -10019.670130, best rearrangement setting 11
Bootstrap[784]: Time 0.132299 seconds, bootstrap likelihood -9945.072629, best rearrangement setting 10
Bootstrap[785]: Time 0.063074 seconds, bootstrap likelihood -10047.569714, best rearrangement setting 7
Bootstrap[786]: Time 0.070614 seconds, bootstrap likelihood -9847.686516, best rearrangement setting 11
Bootstrap[787]: Time 0.166245 seconds, bootstrap likelihood -10135.590901, best rearrangement setting 10
Bootstrap[788]: Time 0.168565 seconds, bootstrap likelihood -10145.892442, best rearrangement setting 13
Bootstrap[789]: Time 0.157098 seconds, bootstrap likelihood -10033.121891, best rearrangement setting 9
Bootstrap[790]: Time 0.070690 seconds, bootstrap likelihood -10007.928572, best rearrangement setting 11
Bootstrap[791]: Time 0.152728 seconds, bootstrap likelihood -10122.045800, best rearrangement setting 11
Bootstrap[792]: Time 0.143371 seconds, bootstrap likelihood -9853.513151, best rearrangement setting 15
Bootstrap[793]: Time 0.152109 seconds, bootstrap likelihood -9954.076219, best rearrangement setting 12
Bootstrap[794]: Time 0.074911 seconds, bootstrap likelihood -9776.695166, best rearrangement setting 14
Bootstrap[795]: Time 0.142334 seconds, bootstrap likelihood -9941.822547, best rearrangement setting 6
Bootstrap[796]: Time 0.146974 seconds, bootstrap likelihood -9949.331236, best rearrangement setting 8
Bootstrap[797]: Time 0.074100 seconds, bootstrap likelihood -9906.083372, best rearrangement setting 9
Bootstrap[798]: Time 0.151762 seconds, bootstrap likelihood -9791.077377, best rearrangement setting 10
Bootstrap[799]: Time 0.152769 seconds, bootstrap likelihood -10173.864932, best rearrangement setting 15
Bootstrap[800]: Time 0.160039 seconds, bootstrap likelihood -9867.131871, best rearrangement setting 12
Bootstrap[801]: Time 0.155271 seconds, bootstrap likelihood -10148.204334, best rearrangement setting 8
Bootstrap[802]: Time 0.167535 seconds, bootstrap likelihood -10012.452269, best rearrangement setting 8
Bootstrap[803]: Time 0.157951 seconds, bootstrap likelihood -9903.696964, best rearrangement setting 13
Bootstrap[804]: Time 0.163304 seconds, bootstrap likelihood -9982.435940, best rearrangement setting 10
Bootstrap[805]: Time 0.146639 seconds, bootstrap likelihood -9638.569787, best rearrangement setting 15
Bootstrap[806]: Time 0.156535 seconds, bootstrap likelihood -9789.125423, best rearrangement setting 11
Bootstrap[807]: Time 0.161424 seconds, bootstrap likelihood -10180.687798, best rearrangement setting 12
Bootstrap[808]: Time 0.068234 seconds, bootstrap likelihood -10104.802626, best rearrangement setting 9
Bootstrap[809]: Time 0.144572 seconds, bootstrap likelihood -9696.715578, best rearrangement setting 10
Bootstrap[810]: Time 0.148378 seconds, bootstrap likelihood -10065.245161, best rearrangement setting 6
Bootstrap[811]: Time 0.150033 seconds, bootstrap likelihood -10229.564117, best rearrangement setting 6
Bootstrap[812]: Time 0.156056 seconds, bootstrap likelihood -9955.347530, best rearrangement setting 6
Bootstrap[813]: Time 0.162830 seconds, bootstrap likelihood -9946.777311, best rearrangement setting 9
Bootstrap[814]: Time 0.066294 seconds, bootstrap likelihood -10076.164372, best rearrangement setting 5
Bootstrap[815]: Time 0.157379 seconds, bootstrap likelihood -9893.832669, best rearrangement setting 14
Bootstrap[816]: Time 0.070655 seconds, bootstrap likelihood -10034.568626, best rearrangement setting 12
Bootstrap[817]: Time 0.163759 seconds, bootstrap likelihood -10033.681954, best rearrangement setting 7
Bootstrap[818]: Time 0.153449 seconds, bootstrap likelihood -9797.964091, best rearrangement setting 13
Bootstrap[819]: Time 0.165792 seconds, bootstrap likelihood -9965.559374, best rearrangement setting 10
Bootstrap[820]: Time 0.071961 seconds, bootstrap likelihood -10387.728951, best rearrangement setting 8
Bootstrap[821]: Time 0.074673 seconds, bootstrap likelihood -10240.161046, best rearrangement setting 8
Bootstrap[822]: Time 0.163767 seconds, bootstrap likelihood -10170.687105, best rearrangement setting 6
Bootstrap[823]: Time 0.145762 seconds, bootstrap likelihood -10096.543288, best rearrangement setting 8
Bootstrap[824]: Time 0.166461 seconds, bootstrap likelihood -10237.108147, best rearrangement setting 13
Bootstrap[825]: Time 0.150630 seconds, bootstrap likelihood -9800.145903, best rearrangement setting 15
Bootstrap[826]: Time 0.163291 seconds, bootstrap likelihood -9804.414450, best rearrangement setting 14
Bootstrap[827]: Time 0.143835 seconds, bootstrap likelihood -9881.081698, best rearrangement setting 5
Bootstrap[828]: Time 0.152427 seconds, bootstrap likelihood -10112.856645, best rearrangement setting 14
Bootstrap[829]: Time 0.152034 seconds, bootstrap likelihood -10121.935924, best rearrangement setting 15
Bootstrap[830]: Time 0.167611 seconds, bootstrap likelihood -9836.169815, best rearrangement setting 8
Bootstrap[831]: Time 0.159124 seconds, bootstrap likelihood -10332.858173, best rearrangement setting 13
Bootstrap[832]: Time 0.202920 seconds, bootstrap likelihood -10139.120171, best rearrangement setting 12
Bootstrap[833]: Time 0.148909 seconds, bootstrap likelihood -9590.107863, best rearrangement setting 10
Bootstrap[834]: Time 0.138620 seconds, bootstrap likelihood -9649.601767, best rearrangement setting 11
Bootstrap[835]: Time 0.162455 seconds, bootstrap likelihood -10248.170711, best rearrangement setting 10
Bootstrap[836]: Time 0.145776 seconds, bootstrap likelihood -9962.904097, best rearrangement setting 8
Bootstrap[837]: Time 0.175051 seconds, bootstrap likelihood -10194.241852, best rearrangement setting 11
Bootstrap[838]: Time 0.169594 seconds, bootstrap likelihood -10146.857414, best rearrangement setting 10
Bootstrap[839]: Time 0.158875 seconds, bootstrap likelihood -10515.071370, best rearrangement setting 13
Bootstrap[840]: Time 0.156124 seconds, bootstrap likelihood -9890.969393, best rearrangement setting 8
Bootstrap[841]: Time 0.150559 seconds, bootstrap likelihood -9696.929323, best rearrangement setting 9
Bootstrap[842]: Time 0.162989 seconds, bootstrap likelihood -10271.454242, best rearrangement setting 12
Bootstrap[843]: Time 0.154521 seconds, bootstrap likelihood -10026.652011, best rearrangement setting 12
Bootstrap[844]: Time 0.139361 seconds, bootstrap likelihood -9832.080667, best rearrangement setting 7
Bootstrap[845]: Time 0.156091 seconds, bootstrap likelihood -10129.548887, best rearrangement setting 13
Bootstrap[846]: Time 0.146887 seconds, bootstrap likelihood -9974.639445, best rearrangement setting 10
Bootstrap[847]: Time 0.161693 seconds, bootstrap likelihood -9629.620093, best rearrangement setting 13
Bootstrap[848]: Time 0.148573 seconds, bootstrap likelihood -10003.712472, best rearrangement setting 8
Bootstrap[849]: Time 0.069415 seconds, bootstrap likelihood -9629.557386, best rearrangement setting 7
Bootstrap[850]: Time 0.144905 seconds, bootstrap likelihood -10127.985062, best rearrangement setting 6
Bootstrap[851]: Time 0.150229 seconds, bootstrap likelihood -10093.086494, best rearrangement setting 7
Bootstrap[852]: Time 0.148101 seconds, bootstrap likelihood -9737.104035, best rearrangement setting 5
Bootstrap[853]: Time 0.166762 seconds, bootstrap likelihood -10017.606636, best rearrangement setting 8
Bootstrap[854]: Time 0.142119 seconds, bootstrap likelihood -9798.816696, best rearrangement setting 9
Bootstrap[855]: Time 0.161349 seconds, bootstrap likelihood -10187.776803, best rearrangement setting 10
Bootstrap[856]: Time 0.157194 seconds, bootstrap likelihood -10098.430835, best rearrangement setting 9
Bootstrap[857]: Time 0.138644 seconds, bootstrap likelihood -9985.227865, best rearrangement setting 9
Bootstrap[858]: Time 0.167910 seconds, bootstrap likelihood -9911.853003, best rearrangement setting 8
Bootstrap[859]: Time 0.078335 seconds, bootstrap likelihood -10291.861595, best rearrangement setting 14
Bootstrap[860]: Time 0.152849 seconds, bootstrap likelihood -10120.272712, best rearrangement setting 13
Bootstrap[861]: Time 0.075205 seconds, bootstrap likelihood -9733.769368, best rearrangement setting 11
Bootstrap[862]: Time 0.150629 seconds, bootstrap likelihood -10051.936249, best rearrangement setting 8
Bootstrap[863]: Time 0.162122 seconds, bootstrap likelihood -9861.163700, best rearrangement setting 14
Bootstrap[864]: Time 0.147156 seconds, bootstrap likelihood -10057.945439, best rearrangement setting 15
Bootstrap[865]: Time 0.156684 seconds, bootstrap likelihood -10001.584754, best rearrangement setting 9
Bootstrap[866]: Time 0.161575 seconds, bootstrap likelihood -9936.114182, best rearrangement setting 12
Bootstrap[867]: Time 0.150969 seconds, bootstrap likelihood -9969.183770, best rearrangement setting 8
Bootstrap[868]: Time 0.072806 seconds, bootstrap likelihood -9818.512990, best rearrangement setting 9
Bootstrap[869]: Time 0.159873 seconds, bootstrap likelihood -10145.153775, best rearrangement setting 7
Bootstrap[870]: Time 0.153989 seconds, bootstrap likelihood -9845.969775, best rearrangement setting 11
Bootstrap[871]: Time 0.158089 seconds, bootstrap likelihood -10109.277994, best rearrangement setting 13
Bootstrap[872]: Time 0.146887 seconds, bootstrap likelihood -10087.056693, best rearrangement setting 11
Bootstrap[873]: Time 0.176442 seconds, bootstrap likelihood -10245.130296, best rearrangement setting 14
Bootstrap[874]: Time 0.157596 seconds, bootstrap likelihood -10032.208608, best rearrangement setting 8
Bootstrap[875]: Time 0.152920 seconds, bootstrap likelihood -10044.658150, best rearrangement setting 8
Bootstrap[876]: Time 0.153380 seconds, bootstrap likelihood -9815.333617, best rearrangement setting 5
Bootstrap[877]: Time 0.164672 seconds, bootstrap likelihood -10262.419424, best rearrangement setting 5
Bootstrap[878]: Time 0.145022 seconds, bootstrap likelihood -9983.268261, best rearrangement setting 7
Bootstrap[879]: Time 0.170323 seconds, bootstrap likelihood -10442.297308, best rearrangement setting 9
Bootstrap[880]: Time 0.153288 seconds, bootstrap likelihood -9963.197464, best rearrangement setting 12
Bootstrap[881]: Time 0.165399 seconds, bootstrap likelihood -9821.588419, best rearrangement setting 6
Bootstrap[882]: Time 0.160186 seconds, bootstrap likelihood -10074.680066, best rearrangement setting 11
Bootstrap[883]: Time 0.156710 seconds, bootstrap likelihood -10008.277991, best rearrangement setting 9
Bootstrap[884]: Time 0.154022 seconds, bootstrap likelihood -9841.817552, best rearrangement setting 15
Bootstrap[885]: Time 0.078023 seconds, bootstrap likelihood -9879.672613, best rearrangement setting 6
Bootstrap[886]: Time 0.158906 seconds, bootstrap likelihood -10116.734396, best rearrangement setting 6
Bootstrap[887]: Time 0.159049 seconds, bootstrap likelihood -9703.403000, best rearrangement setting 10
Bootstrap[888]: Time 0.148161 seconds, bootstrap likelihood -10028.606390, best rearrangement setting 5
Bootstrap[889]: Time 0.152640 seconds, bootstrap likelihood -10078.356235, best rearrangement setting 13
Bootstrap[890]: Time 0.156169 seconds, bootstrap likelihood -9623.531740, best rearrangement setting 14
Bootstrap[891]: Time 0.156462 seconds, bootstrap likelihood -10214.747333, best rearrangement setting 11
Bootstrap[892]: Time 0.155317 seconds, bootstrap likelihood -9878.398480, best rearrangement setting 15
Bootstrap[893]: Time 0.160311 seconds, bootstrap likelihood -10221.839660, best rearrangement setting 7
Bootstrap[894]: Time 0.158773 seconds, bootstrap likelihood -10067.398096, best rearrangement setting 6
Bootstrap[895]: Time 0.152267 seconds, bootstrap likelihood -9939.833354, best rearrangement setting 7
Bootstrap[896]: Time 0.150119 seconds, bootstrap likelihood -10023.899903, best rearrangement setting 14
Bootstrap[897]: Time 0.158834 seconds, bootstrap likelihood -9997.367900, best rearrangement setting 15
Bootstrap[898]: Time 0.165562 seconds, bootstrap likelihood -10094.401664, best rearrangement setting 13
Bootstrap[899]: Time 0.161046 seconds, bootstrap likelihood -10254.794642, best rearrangement setting 5
Bootstrap[900]: Time 0.165458 seconds, bootstrap likelihood -10183.638023, best rearrangement setting 7
Bootstrap[901]: Time 0.161629 seconds, bootstrap likelihood -10298.921420, best rearrangement setting 7
Bootstrap[902]: Time 0.144669 seconds, bootstrap likelihood -9680.774590, best rearrangement setting 6
Bootstrap[903]: Time 0.163201 seconds, bootstrap likelihood -9903.415451, best rearrangement setting 14
Bootstrap[904]: Time 0.165522 seconds, bootstrap likelihood -9676.254598, best rearrangement setting 10
Bootstrap[905]: Time 0.144393 seconds, bootstrap likelihood -9778.825940, best rearrangement setting 12
Bootstrap[906]: Time 0.068560 seconds, bootstrap likelihood -9684.325582, best rearrangement setting 8
Bootstrap[907]: Time 0.162018 seconds, bootstrap likelihood -9882.126720, best rearrangement setting 10
Bootstrap[908]: Time 0.072586 seconds, bootstrap likelihood -10050.879717, best rearrangement setting 5
Bootstrap[909]: Time 0.168779 seconds, bootstrap likelihood -9914.241114, best rearrangement setting 10
Bootstrap[910]: Time 0.074299 seconds, bootstrap likelihood -10339.794101, best rearrangement setting 14
Bootstrap[911]: Time 0.158999 seconds, bootstrap likelihood -10135.325564, best rearrangement setting 12
Bootstrap[912]: Time 0.076779 seconds, bootstrap likelihood -9407.900230, best rearrangement setting 7
Bootstrap[913]: Time 0.169052 seconds, bootstrap likelihood -9729.400569, best rearrangement setting 15
Bootstrap[914]: Time 0.156472 seconds, bootstrap likelihood -10038.551704, best rearrangement setting 12
Bootstrap[915]: Time 0.167119 seconds, bootstrap likelihood -10137.894239, best rearrangement setting 8
Bootstrap[916]: Time 0.158414 seconds, bootstrap likelihood -9991.486502, best rearrangement setting 5
Bootstrap[917]: Time 0.163053 seconds, bootstrap likelihood -9989.590208, best rearrangement setting 10
Bootstrap[918]: Time 0.168957 seconds, bootstrap likelihood -10235.460665, best rearrangement setting 9
Bootstrap[919]: Time 0.172162 seconds, bootstrap likelihood -10320.595131, best rearrangement setting 7
Bootstrap[920]: Time 0.147625 seconds, bootstrap likelihood -9604.247820, best rearrangement setting 15
Bootstrap[921]: Time 0.160359 seconds, bootstrap likelihood -9989.871421, best rearrangement setting 13
Bootstrap[922]: Time 0.160892 seconds, bootstrap likelihood -10105.941245, best rearrangement setting 6
Bootstrap[923]: Time 0.159917 seconds, bootstrap likelihood -10096.224817, best rearrangement setting 5
Bootstrap[924]: Time 0.148360 seconds, bootstrap likelihood -10045.671324, best rearrangement setting 12
Bootstrap[925]: Time 0.145561 seconds, bootstrap likelihood -9994.884396, best rearrangement setting 10
Bootstrap[926]: Time 0.068896 seconds, bootstrap likelihood -9698.458987, best rearrangement setting 8
Bootstrap[927]: Time 0.159827 seconds, bootstrap likelihood -9988.041998, best rearrangement setting 7
Bootstrap[928]: Time 0.154818 seconds, bootstrap likelihood -9947.838680, best rearrangement setting 7
Bootstrap[929]: Time 0.174273 seconds, bootstrap likelihood -9957.046037, best rearrangement setting 7
Bootstrap[930]: Time 0.073631 seconds, bootstrap likelihood -9882.308154, best rearrangement setting 14
Bootstrap[931]: Time 0.162156 seconds, bootstrap likelihood -10403.441190, best rearrangement setting 8
Bootstrap[932]: Time 0.070096 seconds, bootstrap likelihood -9694.100856, best rearrangement setting 12
Bootstrap[933]: Time 0.161770 seconds, bootstrap likelihood -9980.169379, best rearrangement setting 14
Bootstrap[934]: Time 0.151381 seconds, bootstrap likelihood -10083.275627, best rearrangement setting 8
Bootstrap[935]: Time 0.158474 seconds, bootstrap likelihood -9665.126289, best rearrangement setting 13
Bootstrap[936]: Time 0.156483 seconds, bootstrap likelihood -9976.692423, best rearrangement setting 10
Bootstrap[937]: Time 0.153419 seconds, bootstrap likelihood -9905.782846, best rearrangement setting 11
Bootstrap[938]: Time 0.147606 seconds, bootstrap likelihood -9986.810405, best rearrangement setting 11
Bootstrap[939]: Time 0.161492 seconds, bootstrap likelihood -10007.778328, best rearrangement setting 6
Bootstrap[940]: Time 0.165091 seconds, bootstrap likelihood -9982.807701, best rearrangement setting 7
Bootstrap[941]: Time 0.150470 seconds, bootstrap likelihood -9909.366375, best rearrangement setting 11
Bootstrap[942]: Time 0.154216 seconds, bootstrap likelihood -9778.705781, best rearrangement setting 14
Bootstrap[943]: Time 0.162759 seconds, bootstrap likelihood -10085.864731, best rearrangement setting 12
Bootstrap[944]: Time 0.159812 seconds, bootstrap likelihood -9977.020571, best rearrangement setting 15
Bootstrap[945]: Time 0.155718 seconds, bootstrap likelihood -10082.200751, best rearrangement setting 13
Bootstrap[946]: Time 0.066177 seconds, bootstrap likelihood -9983.469092, best rearrangement setting 5
Bootstrap[947]: Time 0.142649 seconds, bootstrap likelihood -9927.161079, best rearrangement setting 11
Bootstrap[948]: Time 0.161017 seconds, bootstrap likelihood -10310.113633, best rearrangement setting 15
Bootstrap[949]: Time 0.155968 seconds, bootstrap likelihood -10303.462714, best rearrangement setting 9
Bootstrap[950]: Time 0.153336 seconds, bootstrap likelihood -9938.539218, best rearrangement setting 10
Bootstrap[951]: Time 0.149003 seconds, bootstrap likelihood -10051.234730, best rearrangement setting 6
Bootstrap[952]: Time 0.148870 seconds, bootstrap likelihood -9799.434079, best rearrangement setting 14
Bootstrap[953]: Time 0.167832 seconds, bootstrap likelihood -10015.955403, best rearrangement setting 8
Bootstrap[954]: Time 0.166620 seconds, bootstrap likelihood -9993.260459, best rearrangement setting 11
Bootstrap[955]: Time 0.157005 seconds, bootstrap likelihood -10239.362023, best rearrangement setting 8
Bootstrap[956]: Time 0.171222 seconds, bootstrap likelihood -10035.419592, best rearrangement setting 10
Bootstrap[957]: Time 0.149277 seconds, bootstrap likelihood -9869.178526, best rearrangement setting 9
Bootstrap[958]: Time 0.156784 seconds, bootstrap likelihood -10282.665355, best rearrangement setting 7
Bootstrap[959]: Time 0.153058 seconds, bootstrap likelihood -9907.547295, best rearrangement setting 6
Bootstrap[960]: Time 0.157519 seconds, bootstrap likelihood -9814.602288, best rearrangement setting 15
Bootstrap[961]: Time 0.164723 seconds, bootstrap likelihood -9892.937509, best rearrangement setting 8
Bootstrap[962]: Time 0.155088 seconds, bootstrap likelihood -10282.071995, best rearrangement setting 5
Bootstrap[963]: Time 0.143669 seconds, bootstrap likelihood -9526.476896, best rearrangement setting 7
Bootstrap[964]: Time 0.148239 seconds, bootstrap likelihood -9940.429541, best rearrangement setting 14
Bootstrap[965]: Time 0.152048 seconds, bootstrap likelihood -9858.526888, best rearrangement setting 12
Bootstrap[966]: Time 0.069500 seconds, bootstrap likelihood -9942.375767, best rearrangement setting 9
Bootstrap[967]: Time 0.165168 seconds, bootstrap likelihood -10035.477598, best rearrangement setting 11
Bootstrap[968]: Time 0.152049 seconds, bootstrap likelihood -9869.082624, best rearrangement setting 9
Bootstrap[969]: Time 0.147522 seconds, bootstrap likelihood -9811.275834, best rearrangement setting 9
Bootstrap[970]: Time 0.150119 seconds, bootstrap likelihood -10133.223162, best rearrangement setting 6
Bootstrap[971]: Time 0.166210 seconds, bootstrap likelihood -10160.293067, best rearrangement setting 12
Bootstrap[972]: Time 0.146697 seconds, bootstrap likelihood -10026.214215, best rearrangement setting 13
Bootstrap[973]: Time 0.157880 seconds, bootstrap likelihood -9736.517175, best rearrangement setting 10
Bootstrap[974]: Time 0.148364 seconds, bootstrap likelihood -10088.791823, best rearrangement setting 8
Bootstrap[975]: Time 0.153642 seconds, bootstrap likelihood -9926.767014, best rearrangement setting 10
Bootstrap[976]: Time 0.166945 seconds, bootstrap likelihood -10172.985544, best rearrangement setting 15
Bootstrap[977]: Time 0.148473 seconds, bootstrap likelihood -9999.241072, best rearrangement setting 12
Bootstrap[978]: Time 0.143793 seconds, bootstrap likelihood -9632.671640, best rearrangement setting 13
Bootstrap[979]: Time 0.159287 seconds, bootstrap likelihood -10125.248738, best rearrangement setting 14
Bootstrap[980]: Time 0.162627 seconds, bootstrap likelihood -10259.566411, best rearrangement setting 9
Bootstrap[981]: Time 0.148212 seconds, bootstrap likelihood -10011.738319, best rearrangement setting 13
Bootstrap[982]: Time 0.167380 seconds, bootstrap likelihood -9960.219197, best rearrangement setting 8
Bootstrap[983]: Time 0.156755 seconds, bootstrap likelihood -9958.922684, best rearrangement setting 7
Bootstrap[984]: Time 0.147353 seconds, bootstrap likelihood -10003.789053, best rearrangement setting 13
Bootstrap[985]: Time 0.154339 seconds, bootstrap likelihood -10058.208116, best rearrangement setting 7
Bootstrap[986]: Time 0.141710 seconds, bootstrap likelihood -9770.823359, best rearrangement setting 10
Bootstrap[987]: Time 0.147210 seconds, bootstrap likelihood -9910.022605, best rearrangement setting 7
Bootstrap[988]: Time 0.159309 seconds, bootstrap likelihood -9979.940050, best rearrangement setting 7
Bootstrap[989]: Time 0.152242 seconds, bootstrap likelihood -9873.719949, best rearrangement setting 15
Bootstrap[990]: Time 0.173165 seconds, bootstrap likelihood -10044.913140, best rearrangement setting 15
Bootstrap[991]: Time 0.074908 seconds, bootstrap likelihood -9830.834613, best rearrangement setting 10
Bootstrap[992]: Time 0.159375 seconds, bootstrap likelihood -9701.971387, best rearrangement setting 9
Bootstrap[993]: Time 0.161959 seconds, bootstrap likelihood -9804.173228, best rearrangement setting 7
Bootstrap[994]: Time 0.149063 seconds, bootstrap likelihood -10003.223602, best rearrangement setting 14
Bootstrap[995]: Time 0.159767 seconds, bootstrap likelihood -9835.394674, best rearrangement setting 9
Bootstrap[996]: Time 0.166320 seconds, bootstrap likelihood -10113.615518, best rearrangement setting 7
Bootstrap[997]: Time 0.147846 seconds, bootstrap likelihood -9866.005172, best rearrangement setting 15
Bootstrap[998]: Time 0.154255 seconds, bootstrap likelihood -9989.978902, best rearrangement setting 5
Bootstrap[999]: Time 0.152495 seconds, bootstrap likelihood -10182.629051, best rearrangement setting 6


Rapid BS search did not converge after 1000 replicates with MRE-based Bootstopping criterion
WRF Average of 100 random splits: 2.757556 %
Overall Time for 1000 Rapid Bootstraps 146.421562 seconds
Average Time per Rapid Bootstrap 0.146422 seconds

Starting ML Search ...

Fast ML optimization finished

Fast ML search Time: 85.863507 seconds

Slow ML Search 0 Likelihood: -10014.506581
Slow ML Search 1 Likelihood: -10014.506581
Slow ML Search 2 Likelihood: -10014.506581
Slow ML Search 3 Likelihood: -10014.506581
Slow ML Search 4 Likelihood: -10014.506581
Slow ML Search 5 Likelihood: -10014.506581
Slow ML Search 6 Likelihood: -10014.506581
Slow ML Search 7 Likelihood: -10014.506581
Slow ML Search 8 Likelihood: -10014.506581
Slow ML Search 9 Likelihood: -10014.506581
Slow ML optimization finished

Slow ML search Time: 2.999446 seconds
Thorough ML search Time: 0.346401 seconds

Final ML Optimization Likelihood: -10014.506677

Model Information:

Model Parameters of Partition 0, Name: No Name Provided, Type of Data: DNA
alpha: 0.553455
Tree-Length: 2.780349
rate A <-> C: 0.678478
rate A <-> G: 1.429370
rate A <-> T: 1.106240
rate C <-> G: 0.738938
rate C <-> T: 3.020142
rate G <-> T: 1.000000

freq pi(A): 0.243057
freq pi(C): 0.233329
freq pi(G): 0.322666
freq pi(T): 0.200948


ML search took 89.235043 secs or 0.024788 hours

Combined Bootstrap and ML search took 235.658681 secs or 0.065461 hours

Drawing Bootstrap Support Values on best-scoring ML tree ...



Found 1 tree in File /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bestTree.KBS.ML



Found 1 tree in File /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bestTree.KBS.ML

Program execution info written to /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_info.KBS.ML
All 1000 bootstrapped trees written to: /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bootstrap.KBS.ML

Best-scoring ML tree written to: /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bestTree.KBS.ML

Best-scoring ML tree with support values written to: /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bipartitions.KBS.ML

Best-scoring ML tree with support values as branch labels written to: /N/dc2/projects/Lennon_Sequences/RpfGenerality/RAxML_bipartitionsBranchLabels.KBS.ML

Overall execution time for full ML analysis: 235.699966 secs or 0.065472 hours or 0.002728 days

